'use strict';function w(g,a,b,d){g.v.ic(g.Wa,a,b,d,void 0)}function B(g,a,b,d){g.v.pa?w(g,a,b,d):g.v.bf()._OnMessageFromDOM({type:"event",component:g.Wa,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function D(g,a,b){g.v.B(g.Wa,a,b)}function E(g,a){for(const [b,d]of a)D(g,b,d)}function F(g){g.Mb||(g.v.Ne(g.Wd),g.Mb=!0)}window.Qa=class{constructor(g,a){this.v=g;this.Wa=a;this.Mb=!1;this.Wd=()=>this.Ca()}Zc(){}Ca(){}};function H(g){-1!==g.Na&&(self.clearTimeout(g.Na),g.Na=-1)}
window.Ee=class{constructor(g,a){this.Gc=g;this.pg=a;this.Na=-1;this.Nb=-Infinity;this.Xd=()=>{this.Na=-1;this.Nb=Date.now();this.ab=!0;this.Gc();this.ab=!1};this.Gd=this.ab=!1}c(){H(this);this.Xd=this.Gc=null}};"use strict";function I(g,a){const b=a.elementId,d=g.cd(b,a);g.Y.set(b,d);a.isVisible||(d.style.display="none");a=g.sc(d);a.addEventListener("focus",()=>{J(g,"elem-focused",b)});a.addEventListener("blur",()=>{J(g,"elem-blurred",b)});g.Hb&&document.body.appendChild(d)}
function K(g,a){D(g,"get-element",b=>{const d=g.Y.get(b.elementId);return a(d,b)})}function J(g,a,b){var d;d||(d={});d.elementId=b;w(g,a,d)}
window.qe=class extends self.Qa{constructor(g,a){super(g,a);this.Y=new Map;this.Hb=!0;E(this,[["create",b=>I(this,b)],["destroy",b=>{{b=b.elementId;const d=this.Y.get(b);this.Hb&&d.parentElement.removeChild(d);this.Y.delete(b)}}],["set-visible",b=>{this.Hb&&(this.Y.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Hb){var d=this.Y.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=b.height+"px";b=b.fontSize;
null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{{const d=this.Y.get(b.elementId);this.oc(d,b)}}],["focus",b=>{{const d=this.sc(this.Y.get(b.elementId));b.focus?d.focus():d.blur()}}],["set-css-style",b=>{this.Y.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.Y.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.Y.get(b.elementId).removeAttribute(b.name)}]]);K(this,b=>b)}cd(){throw Error("required override");}oc(){throw Error("required override");}sc(g){return g}};
"use strict";
{const g=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);function a(u){if(u.zg){const h=document.createElement("script");h.async=!1;h.textContent=u.Cg;document.head.appendChild(h)}else return new Promise((h,k)=>{const c=document.createElement("script");c.onload=h;c.onerror=k;c.async=!1;c.src=u;document.head.appendChild(c)})}let b=new Audio;const d={"audio/webm; codecs=opus":!!b.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!b.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!b.canPlayType("audio/webm; codecs=vorbis"),
"audio/ogg; codecs=vorbis":!!b.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!b.canPlayType("audio/mp4"),"audio/mpeg":!!b.canPlayType("audio/mpeg")};b=null;async function f(u){u=await n(u);return(new TextDecoder("utf-8")).decode(u)}function n(u){return new Promise((h,k)=>{const c=new FileReader;c.onload=e=>h(e.target.result);c.onerror=e=>k(e);c.readAsArrayBuffer(u)})}const q=[];let t=0;window.RealFile=window.File;const x=[],A=new Map,v=new Map;let y=0;const C=[];self.Ng=function(u){if("function"!==
typeof u)throw Error("runOnStartup called without a function");C.push(u)};const z=new Set(["cordova","playable-ad","instant-games"]);window.Ba=class u{constructor(h){this.pa=h.Eg;this.na=null;this.J="";this.Vb=h.Bg;this.pb={};this.ma=this.Ga=this.ob=null;this.Kb=[];this.cb=this.I=this.La=null;this.Ka=-1;this.ug=()=>this.Bf();this.Ja=[];this.P=h.Yd;!this.pa||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation||(this.pa=!1);z.has(this.P)&&this.pa&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.pa=!1);this.Pb=this.ha=null;"html5"!==this.P&&"playable-ad"!==this.P||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.B("runtime","cordova-fetch-local-file",k=>this.kf(k));this.B("runtime","create-job-worker",()=>this.lf());"cordova"===this.P?document.addEventListener("deviceready",()=>this.td(h)):this.td(h)}c(){this.pc();this.na&&(this.na=
this.na.onmessage=null);this.ob&&(this.ob.terminate(),this.ob=null);this.Ga&&(this.Ga.c(),this.Ga=null);this.I&&(this.I.parentElement.removeChild(this.I),this.I=null)}gd(){return g&&"cordova"===this.P}tb(){return g&&z.has(this.P)||navigator.standalone}async td(h){"preview"===this.P&&(this.ma=document.createElement("div"),this.ma.className="previewLoadingMessage",this.ma.textContent=h.Lg,document.body.appendChild(this.ma));if("playable-ad"===this.P){this.ha=self.c3_base64files;this.Pb={};await this.Se();
for(let c=0,e=h.Oa.length;c<e;++c){var k=h.Oa[c].toLowerCase();this.Pb.hasOwnProperty(k)?h.Oa[c]={zg:!0,Cg:this.Pb[k]}:this.ha.hasOwnProperty(k)&&(h.Oa[c]=URL.createObjectURL(this.ha[k]))}}h.wg?this.J=h.wg:(k=location.origin,this.J=("null"===k?"file:///":k)+location.pathname,k=this.J.lastIndexOf("/"),-1!==k&&(this.J=this.J.substr(0,k+1)));if(h.Gg)for(const [c,e]of Object.entries(h.Gg))this.pb[c]=URL.createObjectURL(e);k=new MessageChannel;this.na=k.port1;this.na.onmessage=c=>this._OnMessageFromRuntime(c.data);
window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(c=>this.xf(c));this.cb=new self.Ae(this);await L(this.cb);this.hd();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.pa?await this.df(h,k.port2):await this.cf(h,k.port2)}tc(h){return this.pb.hasOwnProperty(h)?this.pb[h]:h.endsWith("/workermain.js")&&this.pb.hasOwnProperty("workermain.js")?this.pb["workermain.js"]:"playable-ad"===this.P&&
this.ha.hasOwnProperty(h.toLowerCase())?URL.createObjectURL(this.ha[h.toLowerCase()]):h}async ac(h,k,c){if(h.startsWith("blob:"))return new Worker(h,c);if(this.gd()&&"file:"===location.protocol)return h=await this.$b(this.Vb+h),new Worker(URL.createObjectURL(new Blob([h],{type:"application/javascript"})),c);h=new URL(h,k);if(location.origin!==h.origin){h=await fetch(h);if(!h.ok)throw Error("failed to fetch worker script");h=await h.blob();return new Worker(URL.createObjectURL(h),c)}return new Worker(h,
c)}ua(){return Math.max(window.innerWidth,1)}ta(){return Math.max(window.innerHeight,1)}hd(){if(this.tb()){const h=document.documentElement.style,k=document.body.style,c=window.innerWidth<window.innerHeight,e=c?window.screen.width:window.screen.height;k.height=h.height=(c?window.screen.height:window.screen.width)+"px";k.width=h.width=e+"px"}}rd(h){var k=this.cb;return{baseUrl:this.J,windowInnerWidth:this.ua(),windowInnerHeight:this.ta(),devicePixelRatio:window.devicePixelRatio,isFullscreen:u.hc(),
projectData:h.Mg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:h.Yd,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Kg,jobScheduler:{inputPort:k.Mc,outputPort:k.Tc,maxNumWorkers:k.rg},supportedAudioFormats:d,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Vb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Vb+"opus.wasm.wasm",isiOSCordova:this.gd(),isiOSWebView:this.tb(),isFBInstantAvailable:"undefined"!==
typeof self.FBInstant}}async df(h,k){var c=this.tc(h.Fg);this.ob=await this.ac(c,this.J,{name:"Runtime"});this.I=document.createElement("canvas");this.I.style.display="none";c=this.I.transferControlToOffscreen();document.body.appendChild(this.I);window.c3canvas=this.I;this.ob.postMessage(Object.assign(this.rd(h),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:c,workerDependencyScripts:h.Yc||[],engineScripts:h.Oa,projectScripts:window.Jg,projectScriptsStatus:self.C3_ProjectScriptsStatus}),
[k,c,...M(this.cb)]);this.Kb=x.map(e=>new e(this));this.qd();self.c3_callFunction=(e,l)=>this.La.ef(e,l);"preview"===this.P&&(self.goToLastErrorScript=()=>this.ic("runtime","go-to-last-error-script"))}async cf(h,k){this.I=document.createElement("canvas");this.I.style.display="none";document.body.appendChild(this.I);window.c3canvas=this.I;this.Kb=x.map(e=>new e(this));this.qd();const c=h.Oa.map(e=>"string"===typeof e?(new URL(e,this.J)).toString():e);Array.isArray(h.Yc)&&c.unshift(...h.Yc);await Promise.all(c.map(e=>
a(e)));if(h.Zd&&0<h.Zd.length){const e=self.C3_ProjectScriptsStatus;try{if(await Promise.all(h.Zd.map(l=>a(l[1]))),Object.values(e).some(l=>!l)){self.setTimeout(()=>this.Bd(e),100);return}}catch(l){console.error("[Preview] Error loading project scripts: ",l);self.setTimeout(()=>this.Bd(e),100);return}}"preview"===this.P&&"object"!==typeof self.Hg.Ig?(this.Db(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(h=Object.assign(this.rd(h),{isInWorker:!1,messagePort:k,canvas:this.I,runOnStartupFunctions:C}),this.vd(),this.Ga=self.C3_CreateRuntime(h),await self.C3_InitRuntime(this.Ga,h))}Bd(h){this.Db();h=`Failed to load project script '${Object.entries(h).filter(k=>!k[1]).map(k=>k[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+h);alert(h)}vd(){this.Db()}Db(){this.ma&&(this.ma.parentElement.removeChild(this.ma),this.ma=null)}async lf(){const h=await N(this.cb);return{outputPort:h,
transferables:[h]}}bf(){if(this.pa)throw Error("not available in worker mode");return this.Ga}ic(h,k,c,e,l){this.na.postMessage({type:"event",component:h,handler:k,dispatchOpts:e||null,data:c,responseId:null},l)}jd(h,k,c,e,l){const m=y++,p=new Promise((r,G)=>{v.set(m,{resolve:r,reject:G})});this.na.postMessage({type:"event",component:h,handler:k,dispatchOpts:e||null,data:c,responseId:m},l);return p}["_OnMessageFromRuntime"](h){const k=h.type;if("event"===k)return this.rf(h);if("result"===k)this.Ef(h);
else if("runtime-ready"===k)this.Ff();else if("alert-error"===k)this.Db(),alert(h.message);else if("creating-runtime"===k)this.vd();else throw Error(`unknown message '${k}'`);}rf(h){const k=h.component,c=h.handler,e=h.data,l=h.responseId;if(h=A.get(k))if(h=h.get(c)){var m=null;try{m=h(e)}catch(p){console.error(`Exception in '${k}' handler '${c}':`,p);null!==l&&this.Bb(l,!1,""+p);return}if(null===l)return m;m&&m.then?m.then(p=>this.Bb(l,!0,p)).catch(p=>{console.error(`Rejection from '${k}' handler '${c}':`,
p);this.Bb(l,!1,""+p)}):this.Bb(l,!0,m)}else console.warn(`[DOM] No handler '${c}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Bb(h,k,c){let e;c&&c.transferables&&(e=c.transferables);this.na.postMessage({type:"result",responseId:h,isOk:k,result:c},e)}Ef(h){const k=h.responseId,c=h.isOk;h=h.result;const e=v.get(k);c?e.resolve(h):e.reject(h);v.delete(k)}B(h,k,c){let e=A.get(h);e||(e=new Map,A.set(h,e));if(e.has(k))throw Error(`[DOM] Component '${h}' already has handler '${k}'`);
e.set(k,c)}static Pa(h){if(x.includes(h))throw Error("DOM handler already added");x.push(h)}qd(){for(const h of this.Kb)if("runtime"===h.Wa){this.La=h;return}throw Error("cannot find runtime DOM handler");}xf(h){this.ic("debugger","message",h)}Ff(){for(const h of this.Kb)h.Zc()}static hc(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}Ne(h){this.Ja.push(h);this.Ec()}Qf(h){h=this.Ja.indexOf(h);if(-1===h)throw Error("invalid callback");this.Ja.splice(h,
1);this.Ja.length||this.pc()}Ec(){-1===this.Ka&&this.Ja.length&&(this.Ka=requestAnimationFrame(this.ug))}pc(){-1!==this.Ka&&(cancelAnimationFrame(this.Ka),this.Ka=-1)}Bf(){this.Ka=-1;for(const h of this.Ja)h();this.Ec()}sa(h){this.La.sa(h)}Aa(h){this.La.Aa(h)}Dc(){this.La.Dc()}wb(h){this.La.wb(h)}ye(){return!!d["audio/webm; codecs=opus"]}async ng(h){h=await this.jd("runtime","opus-decode",{arrayBuffer:h},null,[h]);return new Float32Array(h)}xe(h){return/^(?:[a-z]+:)?\/\//.test(h)||"data:"===h.substr(0,
5)||"blob:"===h.substr(0,5)}ze(h){return!this.xe(h)}async kf(h){const k=h.filename;switch(h.as){case "text":return await this.pe(k);case "buffer":return await this.$b(k);default:throw Error("unsupported type");}}bd(h){const k=window.cordova.file.applicationDirectory+"www/"+h.toLowerCase();return new Promise((c,e)=>{window.resolveLocalFileSystemURL(k,l=>{l.file(c,e)},e)})}async pe(h){h=await this.bd(h);return await f(h)}qc(){if(q.length&&!(8<=t)){t++;var h=q.shift();this.Te(h.filename,h.Dg,h.yg)}}$b(h){return new Promise((k,
c)=>{q.push({filename:h,Dg:e=>{t--;this.qc();k(e)},yg:e=>{t--;this.qc();c(e)}});this.qc()})}async Te(h,k,c){try{const e=await this.bd(h),l=await n(e);k(l)}catch(e){c(e)}}async Se(){const h=[];for(const [k,c]of Object.entries(this.ha))h.push(this.Re(k,c));await Promise.all(h)}async Re(h,k){if("object"===typeof k)this.ha[h]=new Blob([k.str],{type:k.type}),this.Pb[h]=k.str;else{let c=await this.$e(k);c||(c=this.Ve(k));this.ha[h]=c}}async $e(h){try{return await (await fetch(h)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
k),null}}Ve(h){h=this.Kf(h);return this.Qe(h.data,h.Ag)}Kf(h){var k=h.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var c=h.substring(k+1);k=h.substring(5,k).split(";");h=k[0]||"";const e=k[2];c="base64"===k[1]||"base64"===e?atob(c):decodeURIComponent(c);return{Ag:h,data:c}}Qe(h,k){var c=h.length;let e=c>>2,l=new Uint8Array(c),m=new Uint32Array(l.buffer,0,e),p,r;for(r=p=0;p<e;++p)m[p]=h.charCodeAt(r++)|h.charCodeAt(r++)<<8|h.charCodeAt(r++)<<16|h.charCodeAt(r++)<<24;for(c&=
3;c--;)l[r]=h.charCodeAt(r),++r;return new Blob([l],{type:k})}}}"use strict";
{const g=self.Ba;function a(c){return c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents||c.originalEvent&&c.originalEvent.sourceCapabilities&&c.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},f={dispatchUserScriptEvent:!0},n={dispatchRuntimeEvent:!0};function q(c){return new Promise((e,l)=>{const m=document.createElement("link");m.onload=()=>e(m);m.onerror=p=>l(p);m.rel=
"stylesheet";m.href=c;document.head.appendChild(m)})}function t(c){return new Promise((e,l)=>{const m=new Image;m.onload=()=>e(m);m.onerror=p=>l(p);m.src=c})}async function x(c){c=URL.createObjectURL(c);try{return await t(c)}finally{URL.revokeObjectURL(c)}}function A(c){return new Promise((e,l)=>{let m=new FileReader;m.onload=p=>e(p.target.result);m.onerror=p=>l(p);m.readAsText(c)})}async function v(c,e,l){if(!/firefox/i.test(navigator.userAgent))return await x(c);var m=await A(c);m=(new DOMParser).parseFromString(m,
"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const r=p.getAttribute("width"),G=p.getAttribute("height");if(!r.includes("%")&&!G.includes("%"))return await x(c)}p.setAttribute("width",e+"px");p.setAttribute("height",l+"px");m=(new XMLSerializer).serializeToString(m);c=new Blob([m],{type:"image/svg+xml"});return await x(c)}function y(c){do{if(c.parentNode&&c.hasAttribute("contenteditable"))return!0;c=c.parentNode}while(c);return!1}const C=new Set(["canvas",
"body","html"]);function z(c){C.has(c.target.tagName.toLowerCase())&&c.preventDefault()}function u(c){(c.metaKey||c.ctrlKey)&&c.preventDefault()}self.C3_GetSvgImageSize=async function(c){c=await x(c);if(0<c.width&&0<c.height)return[c.width,c.height];{c.style.position="absolute";c.style.left="0px";c.style.top="0px";c.style.visibility="hidden";document.body.appendChild(c);const e=c.getBoundingClientRect();document.body.removeChild(c);return[e.width,e.height]}};self.C3_RasterSvgImageBlob=async function(c,
e,l,m,p){c=await v(c,e,l);const r=document.createElement("canvas");r.width=m;r.height=p;r.getContext("2d").drawImage(c,0,0,e,l);return r};let h=!1;document.addEventListener("pause",()=>h=!0);document.addEventListener("resume",()=>h=!1);function k(){try{return window.parent&&window.parent.document.hasFocus()}catch(c){return!1}}g.Pa(class extends self.Qa{constructor(c){super(c,"runtime");this.Ld=!0;this.Ma=-1;this.Vc="any";this.Cd=this.Dd=!1;this.Pc=this.lb=this.wa=null;c.B("canvas","update-size",m=>
this.If(m));c.B("runtime","invoke-download",m=>this.vf(m));c.B("runtime","raster-svg-image",m=>this.Cf(m));c.B("runtime","get-svg-image-size",m=>this.tf(m));c.B("runtime","set-target-orientation",m=>this.Gf(m));c.B("runtime","register-sw",()=>this.Df());c.B("runtime","post-to-debugger",m=>this.xd(m));c.B("runtime","go-to-script",m=>this.xd(m));c.B("runtime","before-start-ticking",()=>this.jf());c.B("runtime","debug-highlight",m=>this.mf(m));c.B("runtime","enable-device-orientation",()=>this.Pe());
c.B("runtime","enable-device-motion",()=>this.Oe());c.B("runtime","add-stylesheet",m=>this.gf(m));c.B("runtime","alert",m=>this.hf(m));c.B("runtime","hide-cordova-splash",()=>this.uf());const e=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;e.has(p.tagName.toLowerCase())||y(p)||m.preventDefault()});const l=c.I;window.addEventListener("selectstart",z);window.addEventListener("gesturehold",z);l.addEventListener("selectstart",z);l.addEventListener("gesturehold",
z);window.addEventListener("touchstart",z,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",z,{passive:!1}),l.addEventListener("pointerdown",z)):l.addEventListener("touchstart",z);this.ib=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",u,{passive:!1});window.addEventListener("wheel",u,{passive:!1});window.addEventListener("resize",()=>this.Jf());c.tb()&&window.addEventListener("focusout",()=>{{const r=
document.activeElement;if(r){var m=r.tagName.toLowerCase();var p=new Set("email number password search tel text url".split(" "));m="textarea"===m?!0:"input"===m?p.has(r.type.toLowerCase()||"text"):y(r)}else m=!1}m||(document.scrollingElement.scrollTop=0)});this.Ha=new Set;this.Qb=new WeakSet;this.la=!1}jf(){"cordova"===this.v.P?(document.addEventListener("pause",()=>this.Cc(!0)),document.addEventListener("resume",()=>this.Cc(!1))):document.addEventListener("visibilitychange",()=>this.Cc(document.hidden));
return{isSuspended:!(!document.hidden&&!h)}}Zc(){window.addEventListener("focus",()=>this.Cb("window-focus"));window.addEventListener("blur",()=>{this.Cb("window-blur",{parentHasFocus:k()});this.ib=0});window.addEventListener("fullscreenchange",()=>this.yc());window.addEventListener("webkitfullscreenchange",()=>this.yc());window.addEventListener("mozfullscreenchange",()=>this.yc());window.addEventListener("fullscreenerror",e=>this.zc(e));window.addEventListener("webkitfullscreenerror",e=>this.zc(e));
window.addEventListener("mozfullscreenerror",e=>this.zc(e));window.addEventListener("keydown",e=>this.wd("keydown",e));window.addEventListener("keyup",e=>this.wd("keyup",e));window.addEventListener("dblclick",e=>this.Ac("dblclick",e,d));window.addEventListener("wheel",e=>this.zf(e));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",e=>{this.uc(e);this.Ua("pointerdown",e)}),this.v.pa&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.lb=new self.Ee(()=>this.Ye(),
5),this.lb.Gd=!0,window.addEventListener("pointerrawupdate",e=>this.Af(e))):window.addEventListener("pointermove",e=>this.Ua("pointermove",e)),window.addEventListener("pointerup",e=>this.Ua("pointerup",e)),window.addEventListener("pointercancel",e=>this.Ua("pointercancel",e))):(window.addEventListener("mousedown",e=>{this.uc(e);this.Bc("pointerdown",e)}),window.addEventListener("mousemove",e=>this.Bc("pointermove",e)),window.addEventListener("mouseup",e=>this.Bc("pointerup",e)),window.addEventListener("touchstart",
e=>{this.uc(e);this.Ab("pointerdown",e)}),window.addEventListener("touchmove",e=>this.Ab("pointermove",e)),window.addEventListener("touchend",e=>this.Ab("pointerup",e)),window.addEventListener("touchcancel",e=>this.Ab("pointercancel",e)));const c=()=>this.Dc();window.addEventListener("pointerup",c,!0);window.addEventListener("touchend",c,!0);window.addEventListener("click",c,!0);window.addEventListener("keydown",c,!0);window.addEventListener("gamepadconnected",c,!0)}Cb(c,e){w(this,c,e||null,n)}ua(){return this.v.ua()}ta(){return this.v.ta()}Jf(){const c=
this.ua(),e=this.ta();this.Cb("window-resize",{innerWidth:c,innerHeight:e,devicePixelRatio:window.devicePixelRatio});this.v.tb()&&(-1!==this.Ma&&clearTimeout(this.Ma),this.yd(c,e,0))}Rf(c,e,l){-1!==this.Ma&&clearTimeout(this.Ma);this.Ma=setTimeout(()=>this.yd(c,e,l),48)}yd(c,e,l){const m=this.ua(),p=this.ta();this.Ma=-1;m!=c||p!=e?this.Cb("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>l&&this.Rf(m,p,l+1)}Gf(c){this.Vc=c.targetOrientation}jg(){const c=this.Vc;
if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(c).catch(e=>console.warn("[Construct 3] Failed to lock orientation: ",e));else try{let e=!1;screen.lockOrientation?e=screen.lockOrientation(c):screen.webkitLockOrientation?e=screen.webkitLockOrientation(c):screen.mozLockOrientation?e=screen.mozLockOrientation(c):screen.msLockOrientation&&(e=screen.msLockOrientation(c));e||console.warn("[Construct 3] Failed to lock orientation")}catch(e){console.warn("[Construct 3] Failed to lock orientation: ",
e)}}yc(){const c=g.hc();c&&"any"!==this.Vc&&this.jg();w(this,"fullscreenchange",{isFullscreen:c,innerWidth:this.ua(),innerHeight:this.ta()})}zc(c){console.warn("[Construct 3] Fullscreen request failed: ",c);w(this,"fullscreenerror",{isFullscreen:g.hc(),innerWidth:this.ua(),innerHeight:this.ta()})}Cc(c){c?this.v.pc():this.v.Ec();w(this,"visibilitychange",{hidden:c})}wd(c,e){"Backspace"===e.key&&z(e);const l=b.get(e.code)||e.code;B(this,c,{code:l,key:e.key,which:e.which,repeat:e.repeat,altKey:e.altKey,
ctrlKey:e.ctrlKey,metaKey:e.metaKey,shiftKey:e.shiftKey,timeStamp:e.timeStamp},d)}zf(c){w(this,"wheel",{clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,deltaX:c.deltaX,deltaY:c.deltaY,deltaZ:c.deltaZ,deltaMode:c.deltaMode,timeStamp:c.timeStamp},d)}Ac(c,e,l){a(e)||B(this,c,{button:e.button,buttons:e.buttons,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,timeStamp:e.timeStamp},l)}Bc(c,e){if(!a(e)){var l=this.ib;"pointerdown"===c&&0!==l?c="pointermove":"pointerup"===
c&&0!==e.buttons&&(c="pointermove");B(this,c,{pointerId:1,pointerType:"mouse",button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:e.timeStamp},d);this.ib=e.buttons;this.Ac(e.type,e,f)}}Ua(c,e){if(this.lb&&"pointermove"!==c){var l=this.lb;l.ab||(H(l),l.Nb=Date.now())}l=0;"mouse"===e.pointerType&&(l=this.ib);B(this,c,{pointerId:e.pointerId,pointerType:e.pointerType,
button:e.button,buttons:e.buttons,lastButtons:l,clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,width:e.width||0,height:e.height||0,pressure:e.pressure||0,tangentialPressure:e.tangentialPressure||0,tiltX:e.tiltX||0,tiltY:e.tiltY||0,twist:e.twist||0,timeStamp:e.timeStamp},d);"mouse"===e.pointerType&&(l="mousemove","pointerdown"===c?l="mousedown":"pointerup"===c&&(l="pointerup"),this.Ac(l,e,f),this.ib=e.buttons)}Af(c){this.Pc=c;c=this.lb;if(-1===c.Na){var e=Date.now(),l=e-c.Nb,m=c.pg;
l>=m&&c.Gd?(c.Nb=e,c.ab=!0,c.Gc(),c.ab=!1):c.Na=self.setTimeout(c.Xd,Math.max(m-l,4))}}Ye(){this.Ua("pointermove",this.Pc);this.Pc=null}Ab(c,e){for(let l=0,m=e.changedTouches.length;l<m;++l){const p=e.changedTouches[l];B(this,c,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:e.timeStamp},d)}}uc(c){window!==window.top&&window.focus();this.ud(c.target)&&document.activeElement&&!this.ud(document.activeElement)&&document.activeElement.blur()}ud(c){return!c||c===document||c===window||c===document.body||"canvas"===c.tagName.toLowerCase()}Pe(){this.Dd||(this.Dd=!0,window.addEventListener("deviceorientation",c=>this.pf(c)),window.addEventListener("deviceorientationabsolute",c=>this.qf(c)))}Oe(){this.Cd||(this.Cd=!0,window.addEventListener("devicemotion",
c=>this.nf(c)))}pf(c){w(this,"deviceorientation",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp,webkitCompassHeading:c.webkitCompassHeading,webkitCompassAccuracy:c.webkitCompassAccuracy},d)}qf(c){w(this,"deviceorientationabsolute",{absolute:!!c.absolute,alpha:c.alpha||0,beta:c.beta||0,gamma:c.gamma||0,timeStamp:c.timeStamp},d)}nf(c){let e=null;var l=c.acceleration;l&&(e={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var m=c.accelerationIncludingGravity;m&&(l={x:m.x||
0,y:m.y||0,z:m.z||0});m=null;const p=c.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||0,gamma:p.gamma||0});w(this,"devicemotion",{acceleration:e,accelerationIncludingGravity:l,rotationRate:m,interval:c.interval,timeStamp:c.timeStamp},d)}If(c){const e=this.v,l=e.I;l.style.width=c.styleWidth+"px";l.style.height=c.styleHeight+"px";l.style.marginLeft=c.marginLeft+"px";l.style.marginTop=c.marginTop+"px";e.hd();this.Ld&&(l.style.display="",this.Ld=!1)}vf(c){const e=c.url;c=c.filename;const l=document.createElement("a"),
m=document.body;l.textContent=c;l.href=e;l.download=c;m.appendChild(l);l.click();m.removeChild(l)}async Cf(c){var e=c.imageBitmapOpts;c=await self.C3_RasterSvgImageBlob(c.blob,c.imageWidth,c.imageHeight,c.surfaceWidth,c.surfaceHeight);e=e?await createImageBitmap(c,e):await createImageBitmap(c);return{imageBitmap:e,transferables:[e]}}async tf(c){return await self.C3_GetSvgImageSize(c.blob)}async gf(c){await q(c.url)}Dc(){var c=[...this.Ha];this.Ha.clear();if(!this.la)for(const e of c)(c=e.play())&&
c.catch(()=>{this.Qb.has(e)||this.Ha.add(e)})}sa(c){if("function"!==typeof c.play)throw Error("missing play function");this.Qb.delete(c);let e;try{e=c.play()}catch(l){this.Ha.add(c);return}e&&e.catch(()=>{this.Qb.has(c)||this.Ha.add(c)})}Aa(c){this.Ha.delete(c);this.Qb.add(c)}wb(c){this.la=!!c}uf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}mf(c){if(c.show){this.wa||(this.wa=document.createElement("div"),this.wa.id="inspectOutline",document.body.appendChild(this.wa));
var e=this.wa;e.style.display="";e.style.left=c.left-1+"px";e.style.top=c.top-1+"px";e.style.width=c.width+2+"px";e.style.height=c.height+2+"px";e.textContent=c.name}else this.wa&&(this.wa.style.display="none")}Df(){window.C3_RegisterSW&&window.C3_RegisterSW()}xd(c){window.c3_postToMessagePort&&(c.from="runtime",window.c3_postToMessagePort(c))}ef(c,e){return this.v.jd(this.Wa,"js-invoke-function",{name:c,params:e},void 0,void 0)}hf(c){alert(c.message)}})}"use strict";
async function L(g){if(g.og)throw Error("already initialised");g.og=!0;var a=g.Ub.tc("dispatchworker.js");g.Ic=await g.Ub.ac(a,g.J,{name:"DispatchWorker"});a=new MessageChannel;g.Mc=a.port1;g.Ic.postMessage({type:"_init","in-port":a.port2},[a.port2]);g.Tc=await N(g)}function M(g){return[g.Mc,g.Tc]}
async function N(g){const a=g.Md.length;var b=g.Ub.tc("jobworker.js");b=await g.Ub.ac(b,g.J,{name:"JobWorker"+a});const d=new MessageChannel,f=new MessageChannel;g.Ic.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":f.port2},[d.port2,f.port2]);g.Md.push(b);return f.port1}
self.Ae=class{constructor(g){this.Ub=g;this.J=g.J;this.J="preview"===g.P?this.J+"c3/workers/":this.J+g.Vb;this.rg=Math.min(navigator.hardwareConcurrency||2,16);this.Ic=null;this.Md=[];this.Tc=this.Mc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ba({Eg:!0,Fg:"workermain.js",Oa:["scripts/c3runtime.js"],Bg:"scripts/",Yc:[],Yd:"html5"}));"use strict";
self.Ba.Pa(class extends self.Qa{constructor(g){super(g,"mouse");D(this,"cursor",a=>{document.documentElement.style.cursor=a})}});"use strict";
{const g=180/Math.PI;self.da=class extends self.Qa{constructor(a){super(a,"audio");this.Jb=this.f=null;this.Lb=this.Lc=!1;this.oa=()=>this.kg();this.ba=[];this.C=[];this.ga=null;this.Nd="";this.Od=-1;this.kb=new Map;this.Qc=1;this.la=!1;this.Wc=0;this.Xb=1;this.Jc=0;this.Qd="HRTF";this.Hd="inverse";this.Rd=600;this.Pd=1E4;this.Td=1;this.Jd=this.Uc=!1;this.vg=this.v.ye();this.ca=new Map;this.Ea=new Set;this.Nc=!1;this.Rc="";this.xa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.yf(b,d);this.Ib=null;
self.C3Audio_GetOutputStream=()=>this.sf();self.C3Audio_DOMInterface=this;E(this,[["create-audio-context",b=>this.Ue(b)],["play",b=>this.Lf(b)],["stop",b=>this.hg(b)],["stop-all",()=>this.ig()],["set-paused",b=>this.ag(b)],["set-volume",b=>this.fg(b)],["fade-volume",b=>this.Ze(b)],["set-master-volume",b=>this.Zf(b)],["set-muted",b=>this.$f(b)],["set-silent",b=>this.cg(b)],["set-looping",b=>this.Yf(b)],["set-playback-rate",b=>this.bg(b)],["seek",b=>this.Sf(b)],["preload",b=>this.Mf(b)],["unload",b=>
this.lg(b)],["unload-all",()=>this.mg()],["set-suspended",b=>this.dg(b)],["add-effect",b=>this.od(b)],["set-effect-param",b=>this.Vf(b)],["remove-effects",b=>this.Of(b)],["tick",b=>this.Hf(b)],["load-state",b=>this.wf(b)]])}async Ue(a){a.isiOSCordova&&(this.Uc=!0);this.Wc=a.timeScaleMode;this.Qd=["equalpower","HRTF","soundfield"][a.panningModel];this.Hd=["linear","inverse","exponential"][a.distanceModel];this.Rd=a.refDistance;this.Pd=a.maxDistance;this.Td=a.rolloffFactor;var b={latencyHint:a.latencyHint};
if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.pd();this.f.onstatechange=()=>{"running"!==this.f.state&&this.pd()};this.Jb=this.f.createGain();this.Jb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>this.bc();try{await Promise.all(a.preloadList.map(d=>
this.yb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}pd(){this.Lb||(this.Lc=!1,window.addEventListener("pointerup",this.oa,!0),window.addEventListener("touchend",this.oa,!0),window.addEventListener("click",this.oa,!0),window.addEventListener("keydown",this.oa,!0),this.Lb=!0)}We(){this.Lb&&(this.Lc=!0,window.removeEventListener("pointerup",this.oa,!0),window.removeEventListener("touchend",this.oa,!0),window.removeEventListener("click",
this.oa,!0),window.removeEventListener("keydown",this.oa,!0),this.Lb=!1)}kg(){if(!this.Lc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.We()}}W(){return this.f}bc(){return this.f.currentTime}qa(){return this.Jb}ed(a){return(a=this.ca.get(a.toLowerCase()))?a[0].O():this.qa()}$d(a,b){a=a.toLowerCase();let d=this.ca.get(a);d||(d=[],this.ca.set(a,d));b.Xf(d.length);
b.eg(a);d.push(b);this.Ad(a)}Ad(a){let b=this.qa();const d=this.ca.get(a);if(d&&d.length){b=d[0].O();for(let f=0,n=d.length;f<n;++f){const q=d[f];f+1===n?q.S(this.qa()):q.S(d[f+1].O())}}for(const f of this.ja(a))f.Fe(b);this.xa&&this.Rc===a&&(this.xa.disconnect(),this.xa.connect(b))}rb(){return this.Qc}sb(){return this.la}Wf(){this.Jd=!0}se(a,b){return b?this.v.ng(a).then(d=>{const f=this.f.createBuffer(1,d.length,48E3);f.getChannelData(0).set(d);return f}):new Promise((d,f)=>{this.f.decodeAudioData(a,
d,f)})}sa(a){this.v.sa(a)}Aa(a){this.v.Aa(a)}kd(a){let b=0;for(let d=0,f=this.C.length;d<f;++d){const n=this.C[d];this.C[b]=n;n.K===a?n.c():++b}this.C.length=b}Ge(){let a=0;for(let b=0,d=this.ba.length;b<d;++b){const f=this.ba[b];this.ba[a]=f;f.ra()?f.c():++a}this.ba.length=a}*ja(a){if(a)for(const b of this.C)self.da.te(b.$,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async yb(a,b,d,f,n){for(const q of this.ba)if(q.Sa()===b)return await O(q),q;if(n)return null;f&&(this.Uc||this.Jd)&&
this.Ge();n="audio/webm; codecs=opus"===d&&!this.vg;f&&n&&this.Wf();a=!f||this.Uc||n?new self.ne(this,a,b,d,f,n):new self.le(this,a,b,d,f);this.ba.push(a);await O(a);return a}async rc(a,b,d,f,n){for(const q of this.C)if(q.Sa()===b&&(q.Zb()||n))return q.Ie(f),q;a=await this.yb(a,b,d,n);f="html5"===a.Fc?new self.me(a.i,a,f):new self.oe(a.i,a,f);this.C.push(f);return f}Me(a){let b=this.kb.get(a);if(!b){let d=null;b={Xc:0,promise:new Promise(f=>d=f),resolve:d};this.kb.set(a,b)}b.Xc++}Pf(a){const b=this.kb.get(a);
if(!b)throw Error("expected pending tag");b.Xc--;0===b.Xc&&(b.resolve(),this.kb.delete(a))}nc(a){a||(a=this.Nd);return(a=this.kb.get(a))?a.promise:Promise.resolve()}zb(){if(0<this.Ea.size)F(this);else for(const a of this.C)if(a.fd()){F(this);break}}Ca(){for(var a of this.Ea)a.Ca();a=this.bc();for(var b of this.C)b.Ca(a);b=this.C.filter(d=>d.fd()).map(d=>d.Ra());w(this,"state",{tickCount:this.Od,audioInstances:b,analysers:[...this.Ea].map(d=>d.ve())});0===b.length&&0===this.Ea.size&&this.Mb&&(this.v.Qf(this.Wd),
this.Mb=!1)}jc(a,b,d){w(this,"trigger",{type:a,tag:b,aiid:d})}async Lf(a){const b=a.originalUrl,d=a.url,f=a.type,n=a.isMusic,q=a.tag,t=a.isLooping,x=a.vol,A=a.pos,v=a.panning;let y=a.off;0<y&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),y=y-a.performanceTime/1E3+a.contextTime):y=y-performance.now()/1E3+this.f.currentTime);this.Nd=q;this.Me(q);try{this.ga=await this.rc(b,d,f,q,n),v?(this.ga.vb(!0),this.ga.He(v.x,v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&
this.ga.Je(v.uid)):this.ga.vb(!1),this.ga.Play(t,x,A,y)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Pf(q)}F(this)}hg(a){a=a.tag;for(const b of this.ja(a))b.ka()}ig(){for(const a of this.C)a.ka()}ag(a){const b=a.tag;a=a.paused;for(const d of this.ja(b))a?d.Ta():d.ub();this.zb()}fg(a){const b=a.tag;a=a.vol;for(const d of this.ja(b))d.xb(a)}async Ze(a){const b=a.tag,d=a.vol,f=a.duration;a=a.stopOnEnd;await this.nc(b);for(const n of this.ja(b))n.ue(d,
f,a);this.zb()}Zf(a){this.Qc=a.vol;for(const b of this.C)b.Fb()}$f(a){const b=a.tag;a=a.isMuted;for(const d of this.ja(b))d.ld(a)}cg(a){this.la=a.isSilent;this.v.wb(this.la);for(const b of this.C)b.Eb()}Yf(a){const b=a.tag;a=a.isLooping;for(const d of this.ja(b))d.lc(a)}async bg(a){const b=a.tag;a=a.rate;await this.nc(b);for(const d of this.ja(b))d.nd(a)}async Sf(a){const b=a.tag;a=a.pos;await this.nc(b);for(const d of this.ja(b))d.kc(a)}async Mf(a){const b=a.originalUrl,d=a.url,f=a.type;a=a.isMusic;
try{await this.rc(b,d,f,"",a)}catch(n){console.error("[Construct 3] Audio: error preloading: ",n)}}async lg(a){if(a=await this.yb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.ba.indexOf(a),-1!==a&&this.ba.splice(a,1)}mg(){for(const a of this.ba)a.c();this.ba.length=0}dg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.C)b.mc(a);a&&this.f.suspend&&this.f.suspend()}Hf(a){this.Xb=a.timeScale;this.Jc=a.gameTime;this.Od=a.tickCount;if(0!==this.Wc)for(var b of this.C)b.Da();(b=a.listenerPos)&&
this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const f of this.C)f.fa===a&&f.md(d.x,d.y,d.angle)}}async od(a){var b=a.type;const d=a.tag;var f=a.params;if("filter"===b)f=new self.fe(this,...f);else if("delay"===b)f=new self.de(this,...f);else if("convolution"===b){b=null;try{b=await this.yb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(n){console.log("[Construct 3] Audio: error loading convolution: ",n);return}f=new self.ce(this,b.aa,...f);f.Tf(a.bufferOriginalUrl,
a.bufferType)}else if("flanger"===b)f=new self.ge(this,...f);else if("phaser"===b)f=new self.ie(this,...f);else if("gain"===b)f=new self.he(this,...f);else if("tremolo"===b)f=new self.ke(this,...f);else if("ringmod"===b)f=new self.je(this,...f);else if("distortion"===b)f=new self.ee(this,...f);else if("compressor"===b)f=new self.be(this,...f);else if("analyser"===b)f=new self.ae(this,...f);else throw Error("invalid effect type");this.$d(d,f);this.zd()}Vf(a){const b=a.index,d=a.param,f=a.value,n=a.ramp,
q=a.time;a=this.ca.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,f,n,q),this.zd())}Of(a){a=a.tag.toLowerCase();const b=this.ca.get(a);if(b&&b.length){for(const d of b)d.c();this.ca.delete(a);this.Ad(a)}}Le(a){this.Ea.add(a);this.zb()}Nf(a){this.Ea.delete(a)}zd(){this.Nc||(this.Nc=!0,Promise.resolve().then(()=>this.Xe()))}Xe(){const a={};for(const [b,d]of this.ca)a[b]=d.map(f=>f.Ra());w(this,"fxstate",{fxstate:a});this.Nc=!1}async wf(a){const b=a.saveLoadMode;if(3!==b)for(var d of this.C)d.ra()&&1===
b||(d.ra()||2!==b)&&d.ka();for(const f of this.ca.values())for(const n of f)n.c();this.ca.clear();this.Xb=a.timeScale;this.Jc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.la=a.isSilent;this.v.wb(this.la);this.Qc=a.masterVolume;d=[];for(const f of Object.values(a.effects))d.push(Promise.all(f.map(n=>this.od(n))));await Promise.all(d);await Promise.all(a.playing.map(f=>this.ff(f,b)));this.zb()}async ff(a,b){if(3!==b){var d=a.bufferOriginalUrl,f=a.bufferUrl,n=a.bufferType,
q=a.isMusic,t=a.tag,x=a.isLooping,A=a.volume,v=a.playbackTime;if(!q||1!==b)if(q||2!==b){b=null;try{b=await this.rc(d,f,n,t,q)}catch(y){console.error("[Construct 3] Audio: error loading audio state: ",y);return}b.De(a.pan);b.Play(x,A,v,0);a.isPlaying||b.Ta();b.wc(a)}}}yf(a,b){this.xa&&this.xa.disconnect();this.Rc=b.toLowerCase();this.xa=this.f.createMediaStreamSource(a);this.xa.connect(this.ed(this.Rc))}sf(){this.Ib||(this.Ib=this.f.createMediaStreamDestination(),this.Jb.connect(this.Ib));return this.Ib.stream}static te(a,
b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Ke(a){return a*g}static re(a){return Math.pow(10,a/20)}static dd(a){return Math.max(Math.min(self.da.re(a),1),0)}static Ce(a){return Math.log(a)/Math.log(10)*20}static Be(a){return self.da.Ce(Math.max(Math.min(a,1),0))}static xg(a,b){return 1-Math.exp(-b*a)}};self.Ba.Pa(self.da)}"use strict";function O(g){g.Ob||(g.Ob=g.vc());return g.Ob}
self.$c=class{constructor(g,a,b,d,f){this.i=g;this.tg=a;this.ya=b;this.R=d;this.qg=f;this.Fc="";this.Ob=null}c(){this.Ob=this.i=null}vc(){}W(){return this.i.W()}dc(){return this.tg}Sa(){return this.ya}cc(){return this.R}ra(){return this.qg}ea(){}};"use strict";
self.le=class extends self.$c{constructor(g,a,b,d,f){super(g,a,b,d,f);this.Fc="html5";this.H=new Audio;this.H.crossOrigin="anonymous";this.H.autoplay=!1;this.H.preload="auto";this.eb=this.fb=null;this.H.addEventListener("canplaythrough",()=>!0);this.jb=this.W().createGain();this.hb=null;this.H.addEventListener("canplay",()=>{this.fb&&(this.fb(),this.eb=this.fb=null);!this.hb&&this.H&&(this.hb=this.W().createMediaElementSource(this.H),this.hb.connect(this.jb))});this.onended=null;this.H.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.H.addEventListener("error",n=>{console.error(`[Construct 3] Audio '${this.ya}' error: `,n);this.eb&&(this.eb(n),this.eb=this.fb=null)})}c(){this.i.kd(this);this.jb.disconnect();this.jb=null;this.hb.disconnect();this.hb=null;this.H&&!this.H.paused&&this.H.pause();this.H=this.onended=null;super.c()}vc(){return new Promise((g,a)=>{this.fb=g;this.eb=a;this.H.src=this.ya})}N(){return this.H}ea(){return this.H.duration}};"use strict";
async function P(g){if(g.va)return g.va;var a=g.i.v;if("cordova"===a.P&&a.ze(g.ya)&&"file:"===location.protocol)g.va=await a.$b(g.ya);else{a=await fetch(g.ya);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);g.va=await a.arrayBuffer()}}async function Q(g){if(g.aa)return g.aa;g.aa=await g.i.se(g.va,g.sg);g.va=null}
self.ne=class extends self.$c{constructor(g,a,b,d,f,n){super(g,a,b,d,f);this.Fc="webaudio";this.aa=this.va=null;this.sg=!!n}c(){this.i.kd(this);this.aa=this.va=null;super.c()}async vc(){try{await P(this),await Q(this)}catch(g){console.error(`[Construct 3] Failed to load audio '${this.ya}': `,g)}}ea(){return this.aa?this.aa.duration:0}};"use strict";
{let g=0;self.ad=class{constructor(a,b,d){this.i=a;this.K=b;this.$=d;this.Gb=g++;this.L=this.W().createGain();this.L.connect(this.qa());this.A=null;this.bb=!1;this.F=!0;this.V=this.ia=this.D=!1;this.nb=1;this.Fa=!1;this.Z=1;a=this.i.Wc;this.Oc=1===a&&!this.ra()||2===a;this.Za=this.fa=-1;this.Vd=!1}c(){this.K=this.i=null;this.A&&(this.A.disconnect(),this.A=null);this.L.disconnect();this.L=null}W(){return this.i.W()}qa(){return this.i.ed(this.$)}rb(){return this.i.rb()}qb(){return this.Oc?this.i.Jc:
performance.now()/1E3}dc(){return this.K.dc()}Sa(){return this.K.Sa()}cc(){return this.K.cc()}ra(){return this.K.ra()}Ie(a){this.$=a}T(){}Zb(){}IsPlaying(){return!this.F&&!this.D&&!this.T()}fd(){return!this.F&&!this.T()}za(){}ea(){return this.K.ea()}Play(){}ka(){}Ta(){}ub(){}xb(a){this.nb=a;this.L.gain.cancelScheduledValues(0);this.Za=-1;this.L.gain.value=this.ec()}ue(a,b,d){if(!this.Fa){a*=this.rb();var f=this.L.gain;f.cancelScheduledValues(0);var n=this.i.bc();b=n+b;f.setValueAtTime(f.value,n);
f.linearRampToValueAtTime(a,b);this.nb=a;this.Za=b;this.Vd=d}}Fb(){this.xb(this.nb)}Ca(a){-1!==this.Za&&a>=this.Za&&(this.Za=-1,this.Vd&&this.ka(),this.i.jc("fade-ended",this.$,this.Gb))}ec(){const a=this.nb*this.rb();return isFinite(a)?a:0}ld(a){a=!!a;this.Fa!==a&&(this.Fa=a,this.Eb())}sb(){return this.i.sb()}Eb(){}lc(){}nd(a){this.Z!==a&&(this.Z=a,this.Da())}Da(){}kc(){}mc(){}vb(a){a=!!a;this.bb!==a&&((this.bb=a)?(this.A||(this.A=this.W().createPanner(),this.A.panningModel=this.i.Qd,this.A.distanceModel=
this.i.Hd,this.A.refDistance=this.i.Rd,this.A.maxDistance=this.i.Pd,this.A.rolloffFactor=this.i.Td),this.L.disconnect(),this.L.connect(this.A),this.A.connect(this.qa())):(this.A.disconnect(),this.L.disconnect(),this.L.connect(this.qa())))}He(a,b,d,f,n,q){this.bb&&(this.md(a,b,d),a=self.da.Ke,this.A.coneInnerAngle=a(f),this.A.coneOuterAngle=a(n),this.A.coneOuterGain=q)}md(a,b,d){this.bb&&(this.A.setPosition(a,b,0),this.A.setOrientation(Math.cos(d),Math.sin(d),0))}Je(a){this.fa=a}fc(){}Fe(a){const b=
this.A||this.L;b.disconnect();b.connect(a)}Ra(){return{aiid:this.Gb,tag:this.$,duration:this.ea(),volume:this.nb,isPlaying:this.IsPlaying(),playbackTime:this.za(),playbackRate:this.Z,uid:this.fa,bufferOriginalUrl:this.dc(),bufferUrl:"",bufferType:this.cc(),isMusic:this.ra(),isLooping:this.V,isMuted:this.Fa,resumePosition:this.fc(),pan:this.we()}}wc(a){this.nd(a.playbackRate);this.ld(a.isMuted)}we(){if(!this.A)return null;const a=this.A;return{pos:[a.positionX.value,a.positionY.value,a.positionZ.value],
orient:[a.orientationX.value,a.orientationY.value,a.orientationZ.value],cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}De(a){a?(this.vb(!0),a=this.A,a.setPosition(...a.pos),a.setOrientation(...a.orient),a.coneInnerAngle=a.cia,a.coneOuterAngle=a.coa,a.coneOuterGain=a.cog,this.fa=a.uid):this.vb(!1)}}}"use strict";
self.me=class extends self.ad{constructor(g,a,b){super(g,a,b);this.K.jb.connect(this.L);this.K.onended=()=>this.xc()}c(){this.ka();this.K.jb.disconnect();super.c()}N(){return this.K.N()}xc(){this.F=!0;this.fa=-1;this.i.jc("ended",this.$,this.Gb)}T(){return this.N().ended}Zb(){return this.F?!0:this.T()}za(g){let a=this.N().currentTime;g&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(g,a,b){const d=this.N();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==g&&(d.loop=g);this.xb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(f){console.warn(`[Construct 3] Exception seeking audio '${this.K.Sa()}' to position '${b}': `,f)}this.i.sa(d);this.D=this.F=!1;this.V=g;this.Z=1}ka(){const g=this.N();g.paused||g.pause();this.i.Aa(g);this.F=!0;this.D=!1;this.fa=-1}Ta(){if(!(this.D||this.F||this.T())){var g=this.N();g.paused||g.pause();this.i.Aa(g);this.D=!0}}ub(){!this.D||this.F||this.T()||(this.i.sa(this.N()),this.D=!1)}Eb(){this.N().muted=this.Fa||this.sb()}lc(g){g=!!g;
this.V!==g&&(this.V=g,this.N().loop=g)}Da(){let g=this.Z;this.Oc&&(g*=this.i.Xb);try{this.N().playbackRate=g}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${g}':`,a)}}kc(g){if(!this.F&&!this.T())try{this.N().currentTime=g}catch(a){console.warn(`[Construct 3] Error seeking audio to '${g}': `,a)}}fc(){return this.za()}mc(g){g?this.IsPlaying()?(this.N().pause(),this.ia=!0):this.ia=!1:this.ia&&(this.i.sa(this.N()),this.ia=!1)}};"use strict";
function R(g){g.j&&g.j.disconnect();g.j=null;g.Va=null}
self.oe=class extends self.ad{constructor(g,a,b){super(g,a,b);this.j=null;this.Rb=d=>this.xc(d);this.Kc=!0;this.Va=null;this.M=this.Wb=0;this.Sc=1}c(){this.ka();R(this);this.Rb=null;super.c()}xc(g){this.D||this.ia||g.target!==this.Va||(this.F=this.Kc=!0,this.fa=-1,R(this),this.i.jc("ended",this.$,this.Gb))}T(){return!this.F&&this.j&&this.j.loop||this.D?!1:this.Kc}Zb(){return!this.j||this.F?!0:this.T()}za(g){let a;a=this.D?this.M:this.qb()-this.Wb;g&&(a*=this.Z);this.V||(a=Math.min(a,this.ea()));return a}Play(g,
a,b,d){this.Sc=1;this.xb(a);R(this);this.j=this.W().createBufferSource();this.j.buffer=this.K.aa;this.j.connect(this.L);this.Va=this.j;this.j.onended=this.Rb;this.j.loop=g;this.j.start(d,b);this.D=this.F=this.Kc=!1;this.V=g;this.Z=1;this.Wb=this.qb()-b}ka(){if(this.j)try{this.j.stop(0)}catch(g){}this.F=!0;this.D=!1;this.fa=-1}Ta(){this.D||this.F||this.T()||(this.M=this.za(!0),this.V&&(this.M%=this.ea()),this.D=!0,this.j.stop(0))}ub(){!this.D||this.F||this.T()||(R(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.K.aa,this.j.connect(this.L),this.Va=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Fb(),this.Da(),this.Wb=this.qb()-this.M/(this.Z||.001),this.j.start(0,this.M),this.D=!1)}ec(){return super.ec()*this.Sc}Eb(){this.Sc=this.Fa||this.sb()?0:1;this.Fb()}lc(g){g=!!g;this.V!==g&&(this.V=g,this.j&&(this.j.loop=g))}Da(){let g=this.Z;this.Oc&&(g*=this.i.Xb);this.j&&(this.j.playbackRate.value=g)}kc(g){this.F||this.T()||(this.D?this.M=g:(this.Ta(),this.M=g,this.ub()))}fc(){return this.M}mc(g){g?
this.IsPlaying()?(this.ia=!0,this.M=this.za(!0),this.V&&(this.M%=this.ea()),this.j.stop(0)):this.ia=!1:this.ia&&(R(this),this.j=this.W().createBufferSource(),this.j.buffer=this.K.aa,this.j.connect(this.L),this.Va=this.j,this.j.onended=this.Rb,this.j.loop=this.V,this.Fb(),this.Da(),this.Wb=this.qb()-this.M/(this.Z||.001),this.j.start(0,this.M),this.ia=!1)}wc(g){super.wc(g);this.M=g.resumePosition}};"use strict";
{class g{constructor(a){this.i=a;this.f=a.W();this.Kd=-1;this.R=this.$="";this.g=null}c(){this.f=null}Xf(a){this.Kd=a}eg(a){this.$=a}o(){return this.f.createGain()}O(){}S(){}m(a,b,d,f){a.cancelScheduledValues(0);if(0===f)a.value=b;else{var n=this.f.currentTime;f+=n;switch(d){case 0:a.setValueAtTime(b,f);break;case 1:a.setValueAtTime(a.value,n);a.linearRampToValueAtTime(b,f);break;case 2:a.setValueAtTime(a.value,n),a.exponentialRampToValueAtTime(b,f)}}}Ra(){return{type:this.R,tag:this.$,params:this.g}}}
self.fe=class extends g{constructor(a,b,d,f,n,q,t){super(a);this.R="filter";this.g=[b,d,f,n,q,t];this.l=this.o();this.b=this.o();this.b.gain.value=t;this.a=this.o();this.a.gain.value=1-t;this.u=this.f.createBiquadFilter();this.u.type=b;this.u.frequency.value=d;this.u.detune.value=f;this.u.Q.value=n;this.u.gain.vlaue=q;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b)}c(){this.l.disconnect();this.u.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 1:this.g[1]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[2]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[3]=b;this.m(this.u.Q,b,d,f);break;case 4:this.g[4]=b,this.m(this.u.gain,b,d,f)}}};self.de=class extends g{constructor(a,b,d,f){super(a);this.R="delay";this.g=[b,d,f];this.l=
this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=1-f;this.gb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.Ya=this.o();this.Ya.gain.value=d;this.l.connect(this.gb);this.l.connect(this.a);this.gb.connect(this.b);this.gb.connect(this.U);this.U.connect(this.Ya);this.Ya.connect(this.gb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.gb.disconnect();this.U.disconnect();this.Ya.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){const n=self.da.dd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,f);this.m(this.a.gain,1-b,d,f);break;case 4:this.g[1]=n(b);this.m(this.Ya.gain,n(b),d,f);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,f)}}};self.ce=class extends g{constructor(a,b,d,f){super(a);this.R="convolution";this.g=[d,f];this.Fd=this.Ed="";this.l=this.o();this.b=this.o();this.b.gain.value=f;this.a=this.o();this.a.gain.value=
1-f;this.Xa=this.f.createConvolver();this.Xa.normalize=d;this.Xa.buffer=b;this.l.connect(this.Xa);this.l.connect(this.a);this.Xa.connect(this.b)}c(){this.l.disconnect();this.Xa.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}Tf(a,b){this.Ed=a;this.Fd=b}Ra(){const a=
super.Ra();a.bufferOriginalUrl=this.Ed;a.bufferUrl="";a.bufferType=this.Fd;return a}};self.ge=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="flanger";this.g=[b,d,f,n,q];this.l=this.o();this.a=this.o();this.a.gain.value=1-q/2;this.b=this.o();this.b.gain.value=q/2;this.$a=this.o();this.$a.gain.value=n;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=f;this.G=this.o();this.G.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.$a);this.$a.connect(this.U);this.s.connect(this.G);this.G.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();this.$a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 6:this.g[1]=b/1E3;this.m(this.G.gain,b/1E3,d,f);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,f);break;case 8:this.g[3]=b/100,this.m(this.$a.gain,b/100,d,f)}}};self.ie=class extends g{constructor(a,b,d,f,n,q,t){super(a);this.R="phaser";this.g=[b,d,f,n,q,t];this.l=this.o();this.a=this.o();this.a.gain.value=1-t/2;this.b=this.o();this.b.gain.value=t/2;this.u=this.f.createBiquadFilter();this.u.type="allpass";this.u.frequency.value=b;this.u.detune.value=
d;this.u.Q.value=f;this.s=this.f.createOscillator();this.s.frequency.value=q;this.G=this.o();this.G.gain.value=n;this.l.connect(this.u);this.l.connect(this.a);this.u.connect(this.b);this.s.connect(this.G);this.G.connect(this.u.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.u.disconnect();this.s.disconnect();this.G.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,
b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,f);this.m(this.a.gain,1-b/2,d,f);break;case 1:this.g[0]=b;this.m(this.u.frequency,b,d,f);break;case 2:this.g[1]=b;this.m(this.u.detune,b,d,f);break;case 3:this.g[2]=b;this.m(this.u.Q,b,d,f);break;case 6:this.g[3]=b;this.m(this.G.gain,b,d,f);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,f)}}};self.he=class extends g{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,f){const n=self.da.dd;switch(a){case 4:this.g[0]=n(b),this.m(this.h.gain,n(b),d,f)}}};self.ke=class extends g{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.G=this.o();this.G.gain.value=d/2;this.s.connect(this.G);this.G.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.G.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain.value,1-b/2,d,f);this.m(this.G.gain.value,b/2,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.je=class extends g{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.mb=this.o();
this.mb.gain.value=0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.mb.gain);this.s.start(0);this.l.connect(this.mb);this.l.connect(this.a);this.mb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.mb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,
b,d,f);this.m(this.a.gain,1-b,d,f);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,f)}}};self.ee=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="distortion";this.g=[b,d,f,n,q];this.l=this.o();this.Tb=this.o();this.Sb=this.o();this.Uf(f,n);this.b=this.o();this.b.gain.value=q;this.a=this.o();this.a.gain.value=1-q;this.Yb=this.f.createWaveShaper();this.Hc=new Float32Array(65536);this.af(b,d);this.Yb.curve=this.Hc;this.l.connect(this.Tb);this.l.connect(this.a);this.Tb.connect(this.Yb);
this.Yb.connect(this.Sb);this.Sb.connect(this.b)}c(){this.l.disconnect();this.Tb.disconnect();this.Yb.disconnect();this.Sb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Uf(a,b){.01>a&&(a=.01);this.Tb.gain.value=a;this.Sb.gain.value=Math.pow(1/a,.6)*b}af(a,b){for(let d=0;32768>d;++d){let f=d/32768;f=this.gg(f,a,b);this.Hc[32768+d]=f;this.Hc[32768-d-1]=-f}}gg(a,b,d){d=1.05*d*b-b;const f=0>a?-a:a;return(f<b?f:b+d*self.da.xg(f-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}O(){return this.l}X(a,b,d,f){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,f),this.m(this.a.gain,1-b,d,f)}}};self.be=class extends g{constructor(a,b,d,f,n,q){super(a);this.R="compressor";this.g=[b,d,f,n,q];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=f;this.h.attack.value=n;this.h.release.value=q}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}};
self.ae=class extends g{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Id=new Float32Array(this.h.frequencyBinCount);this.Ud=new Uint8Array(b);this.Sd=this.Ia=0;this.i.Le(this)}c(){this.i.Nf(this);this.h.disconnect();super.c()}Ca(){this.h.getFloatFrequencyData(this.Id);this.h.getByteTimeDomainData(this.Ud);const a=this.h.fftSize;let b=this.Ia=0;for(var d=0;d<a;++d){let f=(this.Ud[d]-128)/128;0>f&&(f=-f);
this.Ia<f&&(this.Ia=f);b+=f*f}d=self.da.Be;this.Ia=d(this.Ia);this.Sd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}O(){return this.h}X(){}ve(){return{tag:this.$,index:this.Kd,peak:this.Ia,rms:this.Sd,binCount:this.h.frequencyBinCount,freqBins:this.Id}}}}"use strict";
{function g(a){a.stopPropagation()}self.Ba.Pa(class extends self.qe{constructor(a){super(a,"button")}cd(a,b){const d=document.createElement("input");var f=d;b.isCheckbox?(d.type="checkbox",f=document.createElement("label"),f.appendChild(d),f.appendChild(document.createTextNode("")),f.style.fontFamily="sans-serif",f.style.userSelect="none",f.style.webkitUserSelect="none",f.style.display="inline-block",f.style.color="black"):d.type="button";f.style.position="absolute";f.addEventListener("touchstart",
g);f.addEventListener("touchmove",g);f.addEventListener("touchend",g);f.addEventListener("mousedown",g);f.addEventListener("mouseup",g);f.addEventListener("keydown",g);f.addEventListener("keyup",g);d.addEventListener("click",()=>{var n={isChecked:d.checked};n.elementId=a;B(this,"click",n)});b.id&&(d.id=b.id);this.oc(f,b);return f}sd(a){return"input"===a.tagName.toLowerCase()?a:a.firstChild}sc(a){return this.sd(a)}oc(a,b){const d=this.sd(a);d.checked=b.isChecked;d.disabled=!b.isEnabled;a.title=b.title;
a===d?d.value=b.text:a.lastChild.textContent=b.text}})}"use strict";async function S(g,a){a=a.type;let b=!0;0===a?b=await T():1===a&&(b=await U());w(g,"permission-result",{type:a,result:b})}async function T(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request orientation permission: ",g),!1}}
async function U(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(g){return console.warn("[Touch] Failed to request motion permission: ",g),!1}}self.Ba.Pa(class extends self.Qa{constructor(g){super(g,"touch");D(this,"request-permission",a=>S(this,a))}});