const weaponsCloseCombat = [
    {
        "name": "POWER FIST",
        "nameFantasy": "IRON FIST",
        "nameSciFi": "POWER FIST",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0",
        "attacks": "4",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "BRAWLER",
        "rolesConditionsTextFantasy": "FIGHTER",
        "rolesConditionsTextSciFi": "COMBAT EXPERT",
        "conditions": {
            "type": "",
            "roles": ["BRAWLER"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "DEATH HAMMER",
        "nameFantasy": "DEATH HAMMER",
        "nameSciFi": "DEATH HAMMER",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "0-1",
        "attacks": "4",
        "power": "-",
        "damage": "3",
        "rolesConditionsText": "BRAWLER",
        "rolesConditionsTextFantasy": "FIGHTER",
        "rolesConditionsTextSciFi": "COMBAT EXPERT",
        "conditions": {
            "type": "",
            "roles": ["BRAWLER"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "SPEAR",
        "nameFantasy": "SPEAR",
        "nameSciFi": "SPEAR",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0-2",
        "attacks": "2",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "DOUBLE DAGGERS",
        "nameFantasy": "DOUBLE DAGGERS",
        "nameSciFi": "DOUBLE DAGGERS",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0",
        "attacks": "5",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ASSASSIN",
        "rolesConditionsTextFantasy": "ASSASSIN",
        "rolesConditionsTextSciFi": "ASSASSIN",
        "conditions": {
            "type": "",
            "roles": ["ASSASSIN"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "SAMURAI SWORD",
        "nameFantasy": "SAMURAI SWORD",
        "nameSciFi": "SAMURAI SWORD",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0",
        "attacks": "3",
        "power": "",
        "damage": "1",
        "rolesConditionsText": "ASSASSIN",
        "rolesConditionsTextFantasy": "ASSASSIN",
        "rolesConditionsTextSciFi": "ASSASSIN",
        "conditions": {
            "type": "",
            "roles": ["ASSASSIN"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "BATTLE AXE",
        "nameFantasy": "BATTLE AXE",
        "nameSciFi": "BATTLE AXE",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-1",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "LONG BLADE",
        "nameFantasy": "LONG SWORD",
        "nameSciFi": "POWER SWORD",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-1",
        "attacks": "4",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "LEADER SKILL OR SOLDIER",
        "rolesConditionsTextFantasy": "LEADER SKILL OR KNIGHT",
        "rolesConditionsTextSciFi": "LEADER SKILL OR MARINE",
        "conditions": {
            "type": "or",
            "roles": ["SOLDIER"],
            "skills": ["LEADER"],
            "armour": [],
        },
    },{
        "name": "BATON",
        "nameFantasy": "BATON",
        "nameSciFi": "BATON",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0",
        "attacks": "3",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "KNUCKLE DUSTERS",
        "nameFantasy": "KNUCKLE DUSTERS",
        "nameSciFi": "KNUCKLE DUSTERS",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0",
        "attacks": "3",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "HALBERD",
        "nameFantasy": "HALBERD",
        "nameSciFi": "HALBERD",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-2",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "KNIFE",
        "nameFantasy": "KNIFE",
        "nameSciFi": "KNIFE",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0",
        "attacks": "3",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "STAFF",
        "nameFantasy": "STAFF",
        "nameSciFi": "STAFF",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-1",
        "attacks": "4",
        "power": "",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "MEDIUM BLADE",
        "nameFantasy": "SHORT SWORD",
        "nameSciFi": "MACHETTE",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0",
        "attacks": "3",
        "power": "",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },
];


    