const weaponsRanged = [
    {
        "name": "MEDIUM RANGE SHOT",
        "nameFantasy": "SHORT BOW",
        "nameSciFi": "ASSAULT RIFLE",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "1-12",
        "attacks": "3",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "CLOSE RANGE SHOT",
        "nameFantasy": "CROSSBOW",
        "nameSciFi": "SHOTGUN",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0-6",
        "attacks": "3",
        "power": "+1",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "LONG RANGE SHOT",
        "nameFantasy": "LONG BOW",
        "nameSciFi": "SNIPER RIFLE",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "3-24",
        "attacks": "5",
        "power": "-",
        "damage": "3",
        "rolesConditionsText": "SHARPSHOOTER",
        "rolesConditionsTextFantasy": "ARCHER",
        "rolesConditionsTextSciFi": "SNIPER",
        "conditions": {
            "type": "",
            "roles": ["SHARPSHOOTER"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "HEALING",
        "nameFantasy": "INSTRUMENT",
        "nameSciFi": "NANO BOTS",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-6",
        "attacks": "3",
        "power": "-",
        "damage": "-1",
        "rolesConditionsText": "HEALER\nDAMAGE HEALS HEARTS",
        "rolesConditionsTextFantasy": "HEALER / BARD\nDAMAGE HEALS HEARTS",
        "rolesConditionsTextSciFi": "MEDIC\nDAMAGE HEALS HEARTS",
        "conditions": {
            "type": "",
            "roles": ["HEALER"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "FIRE",
        "nameFantasy": "FLAME SPELL",
        "nameSciFi": "FLAMER",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "1-6",
        "attacks": "4",
        "power": "+1",
        "damage": "2",
        "rolesConditionsText": "DEMOLISHER\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextFantasy": "BATTLE MAGE\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextSciFi": "HEAVY WEAPONS\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "conditions": {
            "type": "",
            "roles": ["DEMOLISHER"],
            "skills": [],
            "armour": ["MEDIUM ARMOUR", "HEAVY ARMOUR"],
        },
    },{
        "name": "BLAST LONG RANGE",
        "nameFantasy": "LIGHTNING STRIKE SPELL",
        "nameSciFi": "ROCKET LAUNCHER",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "6-24",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "DEMOLISHER\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextFantasy": "BATTLE MAGE\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextSciFi": "HEAVY WEAPONS\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "conditions": {
            "type": "",
            "roles": ["DEMOLISHER"],
            "skills": [],
            "armour": ["MEDIUM ARMOUR", "HEAVY ARMOUR"],
        },
    },{
        "name": "BLAST MEDIUM RANGE",
        "nameFantasy": "BLAST SPELL",
        "nameSciFi": "PLASMA GUN",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "3-12",
        "attacks": "4",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "DEMOLISHER\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextFantasy": "BATTLE MAGE\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextSciFi": "HEAVY WEAPONS\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "conditions": {
            "type": "",
            "roles": ["DEMOLISHER"],
            "skills": [],
            "armour": ["MEDIUM ARMOUR", "HEAVY ARMOUR"],
        },
    },{
        "name": "RAPID FIRE",
        "nameFantasy": "HAIL STORM SPELL",
        "nameSciFi": "MINI GUN",
        "actionsToUse": "HEAVY 3 ACTIONS",
        "action": "3",
        "range": "3-18",
        "attacks": "5",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "DEMOLISHER\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextFantasy": "BATTLE MAGE\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "rolesConditionsTextSciFi": "HEAVY WEAPONS\nMUST HAVE MEDIUM / HEAVY ARMOUR",
        "conditions": {
            "type": "",
            "roles": ["DEMOLISHER"],
            "skills": [],
            "armour": ["MEDIUM ARMOUR", "HEAVY ARMOUR"],
        },
    },{
        "name": "AIR ATTACK",
        "nameFantasy": "COMET STRIKE SPELL",
        "nameSciFi": "DRONE STRIKE",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "6-24",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "SCHOLAR",
        "rolesConditionsTextFantasy": "WIZARD",
        "rolesConditionsTextSciFi": "TECHNICIAN",
        "conditions": {
            "type": "",
            "roles": ["SCHOLAR"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "CLOSE RANGE POWERFUL",
        "nameFantasy": "JAVELIN",
        "nameSciFi": "REVOLVER",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-9",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "CLOSE RANGE WEAK SHOT",
        "nameFantasy": "SLINGSHOT",
        "nameSciFi": "PISTOL",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0-9",
        "attacks": "2",
        "power": "-",
        "damage": "1",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "MEDIUM / LONG RANGE SHOT",
        "nameFantasy": "HEAVY CROSS BOW",
        "nameSciFi": "LONG RIFLE",
        "actionsToUse": "MEDIUM 2 ACTIONS",
        "action": "2",
        "range": "0-18",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "SOLDIER",
        "rolesConditionsTextFantasy": "ANY (?KNIGHT?)",
        "rolesConditionsTextSciFi": "MARINE",
        "conditions": {
            "type": "",
            "roles": ["SOLDIER"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "CLOSE RANGE PROJECTILE",
        "nameFantasy": "THROWING STARS",
        "nameSciFi": "THROWING STARS",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0-3",
        "attacks": "4",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "ASSASSIN",
        "conditions": {
            "type": "",
            "roles": ["ASSASSIN"],
            "skills": [],
            "armour": [],
        },
    },{
        "name": "CLOSE RANGE BLADE",
        "nameFantasy": "THROWING KNIVES",
        "nameSciFi": "THROWING KNIVES",
        "actionsToUse": "LIGHT 1 ACTION",
        "action": "1",
        "range": "0-3",
        "attacks": "3",
        "power": "-",
        "damage": "2",
        "rolesConditionsText": "ANY",
        "rolesConditionsTextFantasy": "ANY",
        "rolesConditionsTextSciFi": "ANY",
        "conditions": {
            "type": "",
            "roles": [],
            "skills": [],
            "armour": [],
        },
    },
];