const roles = [
    {
        "name": "SHARPSHOOTER",
        "nameFantasy":"ARCHER",
        "nameSciFi": "SNIPER",
        "ability1": "Re-roll Ranged Attack rolls of 1",
        "ability2": "Always treated as if in Cover",
        "ability3": "If not moving that round, re-roll any number of Attack dice",
        "ability4": "+1 Armour Save rolls",
    },{
        "name": "HEALER",
        "nameFantasy":"HEALER/BARD",
        "nameSciFi": "MEDIC",
        "ability1": "Unlimited medi packs",
        "ability2": "When a healing Action has been carried out, roll 1D6. On a 6 Heal +1 extra Heart",
        "ability3": "If only moving and healing that round, +1 Free Move Action",
        "ability4": "Healing only costs 1 Action",
    },{
        "name": "BRAWLER",
        "nameFantasy":"FIGHTER",
        "nameSciFi": "COMBAT EXPERT",
        "ability1": "When attacked in Close Combat the Brawler can retaliate with 1 Attack dice for free",
        "ability2": "Medium Close Combat Weapon costs 1 Action",
        "ability3": "Heavy Close Combat Weapon costs 2 Actions",
        "ability4": "+1 Power",
    },{
        "name": "SOLDIER",
        "nameFantasy":"KNIGHT",
        "nameSciFi": "MARINE",
        "ability1": "Can choose 2 Ranged Weapons or 2 Close Combat Weapons",
        "ability2": "Carry 1 Free Grenade per battle",
        "ability3": "+1 Attack Characteristic",
        "ability4": "If Soldier causes any lost Hearts, roll 1D6 for each lost. On 5+ make a Free Attack",
    },{
        "name": "ASSASSIN",
        "nameFantasy":"ASSASSIN",
        "nameSciFi": "ASSASSIN",
        "ability1": "If any part of the model is not in line of sight, the Assassin is in Cover",
        "ability2": "Place Assassin anywhere in their half of the battlefield anytime during Round 1",
        "ability3": "If only moved this activation, the Assassin gains +1 Free Attack",
        "ability4": "+1 Damage for all weapons used",
    },{
        "name": "DEMOLISHER",
        "nameFantasy":"BATTLE MAGE",
        "nameSciFi": "HEAVY WEAPONS",
        "ability1": "Visible Warriors within 3” of target receive 1D3 hits (Heavy Weapons only)",
        "ability2": "Overcharge for +2 Actions. Roll 1D6. On a 5+ all hits are critical hits. On a 1, take D3 damage",
        "ability3": "If no Move actions are made in the round, +1 to Attack Characteristic",
        "ability4": "Visible Warriors within 3” of target take 1D3 auto damage (Heavy Weapons only)",
    },{
        "name": "TAMER",
        "nameFantasy":"SHAMAN",
        "nameSciFi": "ANIMAL HANDLER",
        "ability1": "Take any animal into battle",
        "ability2": "Animals can make a Free Move Action towards the Tamer (once per round)",
        "ability3": "If within 3” of animal, the animal can make 1 Free Attack (once per round)",
        "ability4": "Take an extra animal into battle",
    },{
        "name": "SCHOLAR",
        "nameFantasy":"WIZARD",
        "nameSciFi": "TECHNICIAN",
        "ability1": "1 Action per round can choose a visible Warrior and push them 2” in any direction",
        "ability2": "Carry 1 Free Smoke Grenade per battle",
        "ability3": "Once per battle pick a visible spot anywhere on battlefield. 1D6 damage to each within 3”",
        "ability4": "Once per battle move to any visible spot on the battlefield for 2 Actions",
    },
];