const tables = {
    "A": [
        {"number": "01-50", "item": "Potion of healing"},
        {"number": "51-60", "item": "Spell scroll (cantrip)"},
        {"number": "61-70", "item": "Potion of climbing"},
        {"number": "71-90", "item": "Spell scroll (1st level)"},
        {"number": "91-94", "item": "Spell scroll (2nd level)"},
        {"number": "95-98", "item": "Potion of greater healing"},
        {"number": "99", "item": "Bag of holding"},
        {"number": "00", "item": "Driftglobe"}
    ],
    "B": [
        {"number": "01-15", "item": "Potion of greater healing"},
        {"number": "16-22", "item": "Potion of fire breath"},
        {"number": "23-29", "item": "Potion of resistance"},
        {"number": "30-34", "item": "Ammunition, +1"},
        {"number": "35-39", "item": "Potion of animal friendship"},
        {"number": "40-44", "item": "Potion of hill giant strength"},
        {"number": "45-49", "item": "Potion of growth"},
        {"number": "50-54", "item": "Potion of water breathing"},
        {"number": "55-59", "item": "Spell scroll (2nd level)"},
        {"number": "60-64", "item": "Spell scroll (3rd level)"},
        {"number": "65-67", "item": "Bag of holding"},
        {"number": "68-70", "item": "Keoghtom's ointment"},
        {"number": "71-73", "item": "Oil of slipperiness"},
        {"number": "74-75", "item": "Dust of disappearance"},
        {"number": "76-77", "item": "Dust of dryness"},
        {"number": "78-79", "item": "Dust of sneezing and choking"},
        {"number": "80-81", "item": "Elemental gem"},
        {"number": "82-83", "item": "Philter of love"},
        {"number": "84", "item": "Alchemy jug"},
        {"number": "85", "item": "Cap of water breathing"},
        {"number": "86", "item": "Cloak of the manta ray"},
        {"number": "87", "item": "Driftglobe"},
        {"number": "88", "item": "Goggles of night"},
        {"number": "89", "item": "Helm of comprehending languages"},
        {"number": "90", "item": "Immovable rod"},
        {"number": "91", "item": "Lantern of revealing"},
        {"number": "92", "item": "Mariner's armor"},
        {"number": "93", "item": "Mithral armor"},
        {"number": "94", "item": "Potion of poison"},
        {"number": "95", "item": "Ring of swimming"},
        {"number": "96", "item": "Robe of useful items"},
        {"number": "97", "item": "Rope of climbing"},
        {"number": "98", "item": "Saddle of the cavalier"},
        {"number": "99", "item": "Wand of magic detection"},
        {"number": "00", "item": "Wand of secrets"}
    ],
    "C": [
        {"number": "01-15", "item": "Potion of superior healing"},
        {"number": "16-22", "item": "Spell scroll (4th level)"},
        {"number": "23-27", "item": "Ammunition, +2"},
        {"number": "28-32", "item": "Potion of clairvoyance"},
        {"number": "33-37", "item": "Potion of diminution"},
        {"number": "38-42", "item": "Potion of gaseous form"},
        {"number": "43-47", "item": "Potion of frost giant strength"},
        {"number": "48-52", "item": "Potion of stone giant strength"},
        {"number": "53-57", "item": "Potion of heroism"},
        {"number": "58-62", "item": "Potion of invulnerability"},
        {"number": "63-67", "item": "Potion of mind reading"},
        {"number": "68-72", "item": "Spell scroll (5th level)"},
        {"number": "73-75", "item": "Elixir of health"},
        {"number": "76-78", "item": "Oil of etherealness"},
        {"number": "79-81", "item": "Potion of fire giant strength"},
        {"number": "82-84", "item": "Quaal's feather token"},
        {"number": "85-87", "item": "Scroll of protection"},
        {"number": "88-89", "item": "Bag of beans"},
        {"number": "90-91", "item": "Bead of force"},
        {"number": "92", "item": "Chime of opening"},
        {"number": "93", "item": "Decanter of endless water"},
        {"number": "94", "item": "Eyes of minute seeing"},
        {"number": "95", "item": "Folding boat"},
        {"number": "96", "item": "Heward's handy haversack"},
        {"number": "97", "item": "Horseshoes of speed"},
        {"number": "98", "item": "Necklace of fireballs"},
        {"number": "99", "item": "Periapt of health"},
        {"number": "00", "item": "Sending stones"}
    ],
    "D": [
        {"number": "01-20", "item": "Potion of supreme healing"},
        {"number": "21-30", "item": "Potion of invisibility"},
        {"number": "31-40", "item": "Potion of speed"},
        {"number": "41-50", "item": "Spell scroll (6th level)"},
        {"number": "51-57", "item": "Spell scroll (7th level)"},
        {"number": "58-62", "item": "Ammunition, +3"},
        {"number": "63-67", "item": "Oil of sharpness"},
        {"number": "68-72", "item": "Potion of flying"},
        {"number": "73-77", "item": "Potion of cloud giant strength"},
        {"number": "78-82", "item": "Potion of longevity"},
        {"number": "83-87", "item": "Potion of vitality"},
        {"number": "88-92", "item": "Spell scroll (8th level)"},
        {"number": "93-95", "item": "Horseshoes of a zephyr"},
        {"number": "96-98", "item": "Nolzur's marvelous pigments"},
        {"number": "99", "item": "Bag of devouring"},
        {"number": "00", "item": "Portable hole"}
    ],
    "E": [
        {"number": "01-30", "item": "Spell scroll (8th level)"},
        {"number": "31-55", "item": "Potion of storm giant strength"},
        {"number": "56-70", "item": "Potion of supreme healing"},
        {"number": "71-85", "item": "Spell scroll (9th level)"},
        {"number": "86-93", "item": "Universal solvent"},
        {"number": "94-98", "item": "Arrow of slaying"},
        {"number": "99", "item": "Sovereign glue"},
        {"number": "00", "item": "Sovereign glue"}
    ],
    "F": [
        {"number": "01-15", "item": "Weapon, +1"},
        {"number": "16-18", "item": "Shield, +1"},
        {"number": "19-21", "item": "Sentinel shield"},
        {"number": "22-23", "item": "Amulet of proof against detection and location"},
        {"number": "24-25", "item": "Boots of elvenkind"},
        {"number": "26-27", "item": "Boots of striding and springing"},
        {"number": "28-29", "item": "Bracers of archery"},
        {"number": "30-31", "item": "Brooch of shielding"},
        {"number": "32-33", "item": "Broom of flying"},
        {"number": "34-35", "item": "Cloak of elvenkind"},
        {"number": "36-37", "item": "Cloak of protection"},
        {"number": "38-39", "item": "Gauntlets of ogre power"},
        {"number": "40-41", "item": "Hat of disguise"},
        {"number": "42-43", "item": "Javelin of lightning"},
        {"number": "44-45", "item": "Pearl of power"},
        {"number": "46-47", "item": "Rod of the pact keeper, +1"},
        {"number": "48-49", "item": "Slippers of spider climbing"},
        {"number": "50-51", "item": "Staff of the adder"},
        {"number": "52-53", "item": "Staff of the python"},
        {"number": "54-55", "item": "Sword of vengeance"},
        {"number": "56-57", "item": "Trident of fish command"},
        {"number": "58-59", "item": "Wand of magic missiles"},
        {"number": "60-61", "item": "Wand of the war mage, +1"},
        {"number": "62-63", "item": "Wand of web"},
        {"number": "64-65", "item": "Weapon of warning"},
        {"number": "66", "item": "Adamantine armor (chain mail)"},
        {"number": "67", "item": "Adamantine armor (chain shirt)"},
        {"number": "68", "item": "Adamantine armor (scale mail)"},
        {"number": "69", "item": "Bag of tricks (gray)"},
        {"number": "70", "item": "Bag of tricks (rust)"},
        {"number": "71", "item": "Bag of tricks (tan)"},
        {"number": "72", "item": "Boots of the winterlands"},
        {"number": "73", "item": "Circlet of blasting"},
        {"number": "74", "item": "Deck of illusions"},
        {"number": "75", "item": "Eversmoking bottle"},
        {"number": "76", "item": "Eyes of charming"},
        {"number": "77", "item": "Eyes of the eagle"},
        {"number": "78", "item": "Figurine of wondrous power (silver raven)"},
        {"number": "79", "item": "Gem of brightness"},
        {"number": "80", "item": "Gloves of missile snaring"},
        {"number": "81", "item": "Gloves of swimming and climbing"},
        {"number": "82", "item": "Gloves of thievery"},
        {"number": "83", "item": "Headband of intellect"},
        {"number": "84", "item": "Helm of telepathy"},
        {"number": "85", "item": "Instrument of the bards (Doss lute)"},
        {"number": "86", "item": "Instrument of the bards (Fochlucan bandore)"},
        {"number": "87", "item": "Instrument of the bards (Mac-Fuimidh cittern)"},
        {"number": "88", "item": "Medallion of thoughts"},
        {"number": "89", "item": "Necklace of adaptation"},
        {"number": "90", "item": "Periapt of wound closure"},
        {"number": "91", "item": "Pipes of haunting"},
        {"number": "92", "item": "Pipes of the sewers"},
        {"number": "93", "item": "Ring of jumping"},
        {"number": "94", "item": "Ring of mind shielding"},
        {"number": "95", "item": "Ring of warmth"},
        {"number": "96", "item": "Ring of water walking"},
        {"number": "97", "item": "Quiver of Ehlonna"},
        {"number": "98", "item": "Stone of good luck"},
        {"number": "99", "item": "Wind fan"},
        {"number": "00", "item": "Winged boots"}
    ],
    "G": [
        {"number": "01-11", "item": "Weapon, +2"},
        {"number": "12-14", "item": [
            "Figurine of wondrous power (roll d8)",
            [
                {"number": "1", "item": "Bronze griffon"},
                {"number": "2", "item": "Ebony fly"},
                {"number": "3", "item": "Golden lions"},
                {"number": "4", "item": "Ivory goats"},
                {"number": "5", "item": "Marble elephant"},
                {"number": "6-7", "item": "Onyx dog"},
                {"number": "8", "item": "Serpentine owl"}
            ]
        ]},
        {"number": "15", "item": "Adamantine armor (breastplate) "},
        {"number": "16", "item": "Adamantine armor (splint) "},
        {"number": "17", "item": "Amulet of health "},
        {"number": "18", "item": "Armor of vulnerability "},
        {"number": "19", "item": "Arrow-catching shield "},
        {"number": "20", "item": "Belt of dwarvenkind "},
        {"number": "21", "item": "Belt of hill giant strength "},
        {"number": "22", "item": "Berserker axe "},
        {"number": "23", "item": "Boots of levitation "},
        {"number": "24", "item": "Boots of speed "},
        {"number": "25", "item": "Bowl of commanding water elementals "},
        {"number": "26", "item": "Bracers of defense "},
        {"number": "27", "item": "Brazier of commanding fire elementals "},
        {"number": "28", "item": "Cape of the mountebank "},
        {"number": "29", "item": "Censer of controlling air elementals "},
        {"number": "30", "item": "Armor, +1 chain mail "},
        {"number": "31", "item": "Armor of resistance (chain mail) "},
        {"number": "32", "item": "Armor, +1 chain shirt "},
        {"number": "33", "item": "Armor of resistance (chain shirt) "},
        {"number": "34", "item": "Cloak of displacement "},
        {"number": "35", "item": "Cloak of the bat "},
        {"number": "36", "item": "Cube of force "},
        {"number": "37", "item": "Daern's instant fortress "},
        {"number": "38", "item": "Dagger of venom "},
        {"number": "39", "item": "Dimensional shackles "},
        {"number": "40", "item": "Dragon slayer "},
        {"number": "41", "item": "Elven chain "},
        {"number": "42", "item": "Flame tongue "},
        {"number": "43", "item": "Gem of seeing "},
        {"number": "44", "item": "Giant slayer "},
        {"number": "45", "item": "Glamoured studded leather "},
        {"number": "46", "item": "Helm of teleportation "},
        {"number": "47", "item": "Horn of blasting "},
        {"number": "48", "item": "Horn of Valhalla (silver or brass) "},
        {"number": "49", "item": "Instrument of the bards (Canaith mandolin) "},
        {"number": "50", "item": "Instrument of the bards (Cli lyre) "},
        {"number": "51", "item": "Ioun stone (awareness) "},
        {"number": "52", "item": "Ioun stone (protection) "},
        {"number": "53", "item": "Ioun stone (reserve) "},
        {"number": "54", "item": "Ioun stone (sustenance)"},
        {"number": "55", "item": "Iron bands of Bilarro"},
        {"number": "56", "item": "Armor, +1 leather"},
        {"number": "57", "item": "Armor of resistance (leather)"},
        {"number": "58", "item": "Mace of disruption"},
        {"number": "59", "item": "Mace of smiting"},
        {"number": "60", "item": "Mace of terror"},
        {"number": "61", "item": "Mantle of spell resistance"},
        {"number": "62", "item": "Necklace of prayer beads"},
        {"number": "63", "item": "Periapt of proof against poison"},
        {"number": "64", "item": "Ring of animal influence"},
        {"number": "65", "item": "Ring of evasion"},
        {"number": "66", "item": "Ring of feather falling"},
        {"number": "67", "item": "Ring of free action"},
        {"number": "68", "item": "Ring of protection"},
        {"number": "69", "item": "Ring of resistance"},
        {"number": "70", "item": "Ring of spell storing"},
        {"number": "71", "item": "Ring of the ram"},
        {"number": "72", "item": "Ring of X-ray vision"},
        {"number": "73", "item": "Robe of eyes"},
        {"number": "74", "item": "Rod of rulership"},
        {"number": "75", "item": "Rod of the pact keeper, +2"},
        {"number": "76", "item": "Rope of entanglement"},
        {"number": "77", "item": "Armor, +1 scale mail"},
        {"number": "78", "item": "Armor of resistance (scale mail)"},
        {"number": "79", "item": "Shield, +2"},
        {"number": "80", "item": "Shield of missile attraction"},
        {"number": "81", "item": "Staff of charming"},
        {"number": "82", "item": "Staff of healing"},
        {"number": "83", "item": "Staff of swarming insects"},
        {"number": "84", "item": "Staff of the woodlands"},
        {"number": "85", "item": "Staff of withering"},
        {"number": "86", "item": "Stone of controlling earth elementals"},
        {"number": "87", "item": "Sun blade"},
        {"number": "88", "item": "Sword of life stealing"},
        {"number": "89", "item": "Sword of wounding"},
        {"number": "90", "item": "Tentacle rod"},
        {"number": "91", "item": "Vicious weapon"},
        {"number": "92", "item": "Wand of binding"},
        {"number": "93", "item": "Wand of enemy detection"},
        {"number": "94", "item": "Wand of fear"},
        {"number": "95", "item": "Wand of fireballs"},
        {"number": "96", "item": "Wand of lightning bolts"},
        {"number": "97", "item": "Wand of paralysis"},
        {"number": "98", "item": "Wand of the war mage, +2"},
        {"number": "99", "item": "Wand of wonder"},
        {"number": "00", "item": "Wings of flying"}
    ],
    "H": [
        {"number": "01-10", "item": "Weapon, +3"},
        {"number": "11-12", "item": "Amulet of the planes"},
        {"number": "13-14", "item": "Carpet of flying"},
        {"number": "15-16", "item": "Crystal ball (very rare version)"},
        {"number": "17-18", "item": "Ring of regeneration"},
        {"number": "19-20", "item": "Ring of shooting stars"},
        {"number": "21-22", "item": "Ring of telekinesis"},
        {"number": "23-24", "item": "Robe of scintillating colors"},
        {"number": "25-26", "item": "Robe of stars"},
        {"number": "27-28", "item": "Rod of absorption"},
        {"number": "29-30", "item": "Rod of alertness"},
        {"number": "31-32", "item": "Rod of security"},
        {"number": "33-34", "item": "Rod of the pact keeper, +3"},
        {"number": "35-36", "item": "Scimitar of speed"},
        {"number": "37-38", "item": "Shield, +3"},
        {"number": "39-40", "item": "Staff of fire"},
        {"number": "41-42", "item": "Staff of frost"},
        {"number": "43-44", "item": "Staff of power"},
        {"number": "45-46", "item": "Staff of striking"},
        {"number": "47-48", "item": "Staff of thunder and lightning"},
        {"number": "49-50", "item": "Sword of sharpness"},
        {"number": "51-52", "item": "Wand of polymorph"},
        {"number": "53-54", "item": "Wand of the war mage, +3"},
        {"number": "55", "item": "Adamantine armor (half plate)"},
        {"number": "56", "item": "Adamantine armor (plate)"},
        {"number": "57", "item": "Animated shield"},
        {"number": "58", "item": "Belt of fire giant strength"},
        {"number": "59", "item": "Belt of frost (or stone) giant strength"},
        {"number": "60", "item": "Armor, +1 breastplate"},
        {"number": "61", "item": "Armor of resistance (breastplate)"},
        {"number": "62", "item": "Candle of invocation"},
        {"number": "63", "item": "Armor, +2 chain mail"},
        {"number": "64", "item": "Armor, +2 chain shirt"},
        {"number": "65", "item": "Cloak of arachnida"},
        {"number": "66", "item": "Dancing sword"},
        {"number": "67", "item": "Demon armor"},
        {"number": "68", "item": "Dragon scale mail"},
        {"number": "69", "item": "Dwarven plate"},
        {"number": "70", "item": "Dwarven thrower"},
        {"number": "71", "item": "Efreeti bottle"},
        {"number": "72", "item": "Figurine of wondrous power (obsidian steed)"},
        {"number": "73", "item": "Frost brand"},
        {"number": "74", "item": "Helm of brilliance"},
        {"number": "75", "item": "Horn of Valhalla (bronze)"},
        {"number": "76", "item": "Instrument of the bards (Anstruth harp)"},
        {"number": "77", "item": "Ioun stone (absorption)"},
        {"number": "78", "item": "Ioun stone (agility)"},
        {"number": "79", "item": "Ioun stone (fortitude)"},
        {"number": "80", "item": "Ioun stone (insight)"},
        {"number": "81", "item": "Ioun stone (intellect)"},
        {"number": "82", "item": "Ioun stone (leadership)"},
        {"number": "83", "item": "Ioun stone (strength)"},
        {"number": "84", "item": "Armor, +2 leather"},
        {"number": "85", "item": "Manual of bodily health"},
        {"number": "86", "item": "Manual of gainful exercise"},
        {"number": "87", "item": "Manual of golems"},
        {"number": "88", "item": "Manual of quickness of action"},
        {"number": "89", "item": "Mirror of life trapping"},
        {"number": "90", "item": "Nine lives stealer"},
        {"number": "91", "item": "Oathbow"},
        {"number": "92", "item": "Armor, +2 scale mail"},
        {"number": "93", "item": "Spellguard shield"},
        {"number": "94", "item": "Armor, +1 splint"},
        {"number": "95", "item": "Armor of resistance (splint)"},
        {"number": "96", "item": "Armor, +1 studded leather"},
        {"number": "97", "item": "Armor of resistance (studded leather)"},
        {"number": "98", "item": "Tome of clear thought"},
        {"number": "99", "item": "Tome of leadership and influence"},
        {"number": "00", "item": "Tome of understanding"}
    ],
    "I": [
        {"number": "01-05", "item": "Defender"},
        {"number": "06-10", "item": "Hammer of thunderbolts"},
        {"number": "11-15", "item": "Luck blade"},
        {"number": "16-20", "item": "Sword of answering"},
        {"number": "21-23", "item": "Holy avenger"},
        {"number": "24-26", "item": "Ring of djinni summoning"},
        {"number": "27-29", "item": "Ring of invisibility"},
        {"number": "30-32", "item": "Ring of spell turning"},
        {"number": "33-35", "item": "Rod of lordly might"},
        {"number": "36-38", "item": "Staff of the magi"},
        {"number": "39-41", "item": "Vorpal sword"},
        {"number": "42-43", "item": "Belt of cloud giant strength"},
        {"number": "44-45", "item": "Armor, +2 breastplate"},
        {"number": "46-47", "item": "Armor, +3 chain mail"},
        {"number": "48-49", "item": "Armor, +3 chain shirt"},
        {"number": "50-51", "item": "Cloak of invisibility"},
        {"number": "52-53", "item": "Crystal ball (legendary version)"},
        {"number": "54-55", "item": "Armor, +1 half plate"},
        {"number": "56-57", "item": "Iron flask"},
        {"number": "58-59", "item": "Armor, +3 leather"},
        {"number": "60-61", "item": "Armor, +1 plate"},
        {"number": "62-63", "item": "Robe of the archmagi"},
        {"number": "64-65", "item": "Rod of resurrection"},
        {"number": "66-67", "item": "Armor, +1 scale mail"},
        {"number": "68-69", "item": "Scarab of protection"},
        {"number": "70-71", "item": "Armor, +2 splint"},
        {"number": "72-73", "item": "Armor, +2 studded leather"},
        {"number": "74-75", "item": "Well of many worlds"},
        {"number": "76", "item": [
            "Magic armor (roll d12)",
            [
                {"number": "1-2", "item": "Armor, +2 half plate"},
                {"number": "3-4", "item": "Armor, +2 plate"},
                {"number": "5-6", "item": "Armor, +3 studded leather"},
                {"number": "7-8", "item": "Armor, +3 breastplate"},
                {"number": "9-10", "item": "Armor, +3 splint"},
                {"number": "11", "item": "Armor, +3 half plate"},
                {"number": "12", "item": "Armor, +3 plate"}
            ]
        ]},
        {"number": "77", "item": "Apparatus of Kwalish"},
        {"number": "78", "item": "Armor of invulnerability"},
        {"number": "79", "item": "Belt of storm giant strength"},
        {"number": "80", "item": "Cubic gate"},
        {"number": "81", "item": "Deck of many things"},
        {"number": "82", "item": "Efreeti chain"},
        {"number": "83", "item": "Armor of resistance (half plate)"},
        {"number": "84", "item": "Horn of Valhalla (iron)"},
        {"number": "85", "item": "Instrument of the bards (OIIamh harp)"},
        {"number": "86", "item": "Ioun stone (greater absorption)"},
        {"number": "87", "item": "Ioun stone (mastery)"},
        {"number": "88", "item": "Ioun stone (regeneration)"},
        {"number": "89", "item": "Plate armor of etherealness"},
        {"number": "90", "item": "Plate armor of resistance"},
        {"number": "91", "item": "Ring of air elemental command"},
        {"number": "92", "item": "Ring of earth elemental command"},
        {"number": "93", "item": "Ring of fire elemental command"},
        {"number": "94", "item": "Ring of three wishes"},
        {"number": "95", "item": "Ring of water elemental command"},
        {"number": "96", "item": "Sphere of annihilation"},
        {"number": "97", "item": "Talisman of pure good"},
        {"number": "98", "item": "Talisman of the sphere"},
        {"number": "99", "item": "Talisman of ultimate evil"},
        {"number": "00", "item": "Tome of the stilled tongue"}
    ]
};