//Hero,Name,Mana,Modifier,Faction
const decksList = [
{hero: "Doomies", name: "Quick Shot", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Doomies", name: "Exhume", mana: 1, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Doomies", name: "Dreams of Taulot", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Doomies", name: "Slide", mana: 1, modifier: -1, faction: "Taulot"},
{hero: "Doomies", name: "Riposte", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Doomies", name: "Quicksand", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Doomies", name: "Combustion", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Doomies", name: "Dragon Punch", mana: 1, modifier: +0, faction: "Kurumo"},
{hero: "Doomies", name: "Cotlic's Oath", mana: 3, modifier: +0, faction: "Kurumo/Taulot"},
{hero: "Doomies", name: "Boom", mana: 3, modifier: +3, faction: "Kurumo/Taulot"},
{hero: "Kohai", name: "Exhume", mana: 1, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Kohai", name: "Explosive Intervention", mana: 1, modifier: +0, faction: "Kurumo/Taulot"},
{hero: "Kohai", name: "Sacrifice", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Kohai", name: "Decree of Kurumo", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Kohai", name: "Not So Fast", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Kohai", name: "Slide", mana: 2, modifier: -1, faction: "Taulot"},
{hero: "Kohai", name: "Dissent in the Ranks", mana: 2, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Kohai", name: "Topple", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Kohai", name: "Cotlic's Oath", mana: 3, modifier: +0, faction: "Kurumo/Taulot"},
{hero: "Kohai", name: "Release the Beast", mana: 3, modifier: +3, faction: "Kurumo/Taulot"},
{hero: "Vorhild", name: "Dreams of Taulot", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Vorhild", name: "Stone Barricade", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Vorhild", name: "Touch of Liothan", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Vorhild", name: "Fool Me Once", mana: 1, modifier: +1, faction: "Liothan"},
{hero: "Vorhild", name: "Heightened Senses", mana: 1, modifier: +1, faction: "Liothan"},
{hero: "Vorhild", name: "Vorhild's Oath", mana: 1, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Vorhild", name: "Speak with the Spirits", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Vorhild", name: "Sudden Distraction", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Vorhild", name: "Chasm", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Vorhild", name: "The Ermine's Eye", mana: 3, modifier: +3, faction: "Liothan/Taulot"},
{hero: "Nantaca", name: "Underground Tunnels", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Nantaca", name: "Safeguard", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Nantaca", name: "Vorhild's Oath", mana: 1, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Nantaca", name: "Bewitch", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Nantaca", name: "The Strength of the Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Nantaca", name: "Call The Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Nantaca", name: "Torn Banners", mana: 2, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Nantaca", name: "Endless Disciples", mana: 3, modifier: +0, faction: "Liothan/Taulot"},
{hero: "Nantaca", name: "Chasm", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Nantaca", name: "Call of the Queen", mana: 3, modifier: +3, faction: "Liothan/Taulot"},
{hero: "Shaidrus", name: "Whisper of Nupten", mana: 1, modifier: +0, faction: "Nupten"},
{hero: "Shaidrus", name: "Barring the Way", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Shaidrus", name: "Exhaustion", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Shaidrus", name: "Combustion", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Shaidrus", name: "Redirect", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Shaidrus", name: "Materialize", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Shaidrus", name: "Lifesteal", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Shaidrus", name: "Refract", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Shaidrus", name: "Windblast", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Shaidrus", name: "None Shall Enter", mana: 3, modifier: +3, faction: "Kurumo/Nupten"},
{hero: "Kumaya", name: "Release the Spirits", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Kumaya", name: "Swiftness", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Kumaya", name: "Dance of Death", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Kumaya", name: "Vendetta", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Kumaya", name: "Dodge", mana: 2, modifier: +0, faction: "Kurumo"},
{hero: "Kumaya", name: "Nightmares Incarnate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Kumaya", name: "Time Warp", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Kumaya", name: "Gank", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Kumaya", name: "Dragon Punch", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Kumaya", name: "Enter the Void Palace", mana: 3, modifier: +3, faction: "Kurumo/Nupten"},
{hero: "Akhuti", name: "Unfamiliar Terrain", mana: 1, modifier: +2, faction: "Liothan"},
{hero: "Akhuti", name: "Nourish", mana: 1, modifier: +1, faction: "Liothan"},
{hero: "Akhuti", name: "Acrobatics", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Akhuti", name: "Where Faith Falls", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Akhuti", name: "Materialize", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Akhuti", name: "Hurricane Strike", mana: 2, modifier: +0, faction: "Nupten"},
{hero: "Akhuti", name: "Redirect", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Akhuti", name: "Icewall", mana: 3, modifier: +1, faction: "Liothan"},
{hero: "Akhuti", name: "Sudden Distraction", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Akhuti", name: "Word of Nupten", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Ekhrit", name: "Whisper of Nupten", mana: 1, modifier: +0, faction: "Nupten"},
{hero: "Ekhrit", name: "Indoctrinate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Ekhrit", name: "Triumph of the Light", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Ekhrit", name: "Dismiss", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Ekhrit", name: "Time Warp", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Ekhrit", name: "Snowblind", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Ekhrit", name: "Overflow", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Ekhrit", name: "Nature Reclaims", mana: 3, modifier: -1, faction: "Liothan"},
{hero: "Ekhrit", name: "Windblast", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Ekhrit", name: "Eye of the Storm", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Setheru", name: "Psychic Vampirism", mana: 0, modifier: +2, faction: "Neutral"},
{hero: "Setheru", name: "Skytear Discharge", mana: 0, modifier: +2, faction: "Neutral"},
{hero: "Setheru", name: "Release the Spirits", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Setheru", name: "Shattermind", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Setheru", name: "Soul Transfer", mana: 2, modifier: +0, faction: "Nupten"},
{hero: "Setheru", name: "Indoctrinate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Setheru", name: "Combustion", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Setheru", name: "Disrupt", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Setheru", name: "Soul Scream", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Setheru", name: "Last Judgment", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Shafathi", name: "Psychic Vampirism", mana: 0, modifier: +2, faction: "Neutral"},
{hero: "Shafathi", name: "Clear Mind", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Shafathi", name: "Shattermind", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Shafathi", name: "Down to Earth", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Shafathi", name: "Migraine", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Shafathi", name: "Lifesteal", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Shafathi", name: "Soul Transfer", mana: 2, modifier: +0, faction: "Nupten"},
{hero: "Shafathi", name: "Reave", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Shafathi", name: "Soul Scream", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Shafathi", name: "Flashback", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Haburat", name: "Psychic Shield", mana: 0, modifier: +3, faction: "Neutral"},
{hero: "Haburat", name: "Crippling Precision", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Haburat", name: "Time Glitch", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Haburat", name: "Time Warp", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Haburat", name: "Down to Earth", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Haburat", name: "Burning Rage", mana: 2, modifier: +0, faction: "Kurumo"},
{hero: "Haburat", name: "Materialize", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Haburat", name: "Unstoppable", mana: 3, modifier: +1, faction: "Kurumo"},
{hero: "Haburat", name: "Dragon Punch", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Haburat", name: "Blades of Lightning", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Khenui", name: "Whisper of Nupten", mana: 1, modifier: +0, faction: "Nupten"},
{hero: "Khenui", name: "Unfamiliar Terrain", mana: 1, modifier: +2, faction: "Liothan"},
{hero: "Khenui", name: "Nightmares Incarnate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Khenui", name: "Presence", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Khenui", name: "Bewitch", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Khenui", name: "Indoctrinate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Khenui", name: "Soul Swap", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Khenui", name: "Refract", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Khenui", name: "Nature Reclaims", mana: 3, modifier: -1, faction: "Liothan"},
{hero: "Khenui", name: "Echo Dance", mana: 3, modifier: +3, faction: "Nupten"},
{hero: "Nelaclen", name: "Stone Barricade", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Nelaclen", name: "Eye of the Guardian", mana: 1, modifier: +0, faction: "Liothan/Taulot"},
{hero: "Nelaclen", name: "Overflow", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Nelaclen", name: "Gathering Storm", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Nelaclen", name: "Crawling Darkness", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Nelaclen", name: "Unburial Rites", mana: 2, modifier: -1, faction: "Taulot"},
{hero: "Nelaclen", name: "Xotlan Hungers", mana: 2, modifier: +0, faction: "Taulot"},
{hero: "Nelaclen", name: "Sinkhole", mana: 3, modifier: +0, faction: "Taulot"},
{hero: "Nelaclen", name: "Nature Reclaims", mana: 3, modifier: -1, faction: "Liothan"},
{hero: "Nelaclen", name: "Consulting the Heart", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Achla", name: "Clear Mind", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Achla", name: "Dreams of Taulot", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Achla", name: "Impervious", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Achla", name: "Smelt Armor", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Achla", name: "Exhume", mana: 1, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Achla", name: "Xotlan Hungers", mana: 2, modifier: +0, faction: "Taulot"},
{hero: "Achla", name: "Blazing Edge", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Achla", name: "Reave", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Achla", name: "Unstoppable", mana: 3, modifier: +1, faction: "Kurumo"},
{hero: "Achla", name: "Coma Toxin", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Tlakali", name: "Vorhild's Oath", mana: 1, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Tlakali", name: "Sacrifice", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Tlakali", name: "Freeze", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Tlakali", name: "Coup", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Tlakali", name: "Crawling Darkness", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Tlakali", name: "Snowblind", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Tlakali", name: "The Strength of the Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Tlakali", name: "Topple", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Tlakali", name: "Endless Disciples", mana: 3, modifier: +0, faction: "Liothan/Taulot"},
{hero: "Tlakali", name: "The Thousandth Ritual", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Cotlic", name: "Guerrilla Tactics", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Cotlic", name: "Doom", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Cotlic", name: "Release the Spirits", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Cotlic", name: "Quick Shot", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Cotlic", name: "Grasp of Graphite", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Cotlic", name: "Granite Skin", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Cotlic", name: "Lord of the Many", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Cotlic", name: "Rampant Hatred", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Cotlic", name: "Cotlic's Oath", mana: 3, modifier: +0, faction: "Kurumo/Taulot"},
{hero: "Cotlic", name: "My Kingdom", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Ixatosk", name: "Call The Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Ixatosk", name: "Presence", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Ixatosk", name: "Topple", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Ixatosk", name: "Sudden Distraction", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Ixatosk", name: "Grasp of Graphite", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Ixatosk", name: "Sacrifice", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Ixatosk", name: "Shield Slam", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Ixatosk", name: "Triumph Of The Wild", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Ixatosk", name: "Underground Tunnels", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Ixatosk", name: "From Below", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Zacoal", name: "Stone Barricade", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Zacoal", name: "Impervious", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Zacoal", name: "Amulet of Immovability", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Zacoal", name: "Safeguard", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Zacoal", name: "Dissent in the Ranks", mana: 2, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Zacoal", name: "Xotlan Hungers", mana: 2, modifier: +0, faction: "Taulot"},
{hero: "Zacoal", name: "Slide", mana: 2, modifier: -1, faction: "Taulot"},
{hero: "Zacoal", name: "Gank", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Zacoal", name: "Sinkhole", mana: 3, modifier: +0, faction: "Taulot"},
{hero: "Zacoal", name: "Totemic Slam", mana: 3, modifier: +3, faction: "Taulot"},
{hero: "Corjof", name: "Acrobatics", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Corjof", name: "Espionage", mana: 1, modifier: +1, faction: "Liothan"},
{hero: "Corjof", name: "Presence", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Corjof", name: "Shove", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Corjof", name: "The Strength Of The Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Corjof", name: "Featherstorm", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Corjof", name: "Icewall", mana: 3, modifier: +1, faction: "Liothan"},
{hero: "Corjof", name: "Cull The Weak", mana: 2, modifier: +0, faction: "Nupten"},
{hero: "Corjof", name: "Migraine", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Corjof", name: "Twister Of Souls", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Freyhel", name: "Charm", mana: 1, modifier: +2, faction: "Liothan"},
{hero: "Freyhel", name: "Nourish", mana: 1, modifier: +1, faction: "Liothan"},
{hero: "Freyhel", name: "Shelter", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Freyhel", name: "Breath Of Life", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Freyhel", name: "Shove", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Freyhel", name: "Cooling Breeze", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Freyhel", name: "Glacial Rebirth", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Freyhel", name: "Guide", mana: 3, modifier: +1, faction: "Liothan"},
{hero: "Freyhel", name: "Mud Flood", mana: 3, modifier: +0, faction: "Taulot"},
{hero: "Freyhel", name: "Torn Banners", mana: 2, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Brylvar", name: "Touch Of Liothan", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Brylvar", name: "Torn Banners", mana: 2, modifier: -1, faction: "Liothan/Taulot"},
{hero: "Brylvar", name: "Shove", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Brylvar", name: "Avalanche", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Brylvar", name: "Endless Disciples", mana: 3, modifier: +0, faction: "Liothan/Taulot"},
{hero: "Brylvar", name: "Amulet Of Immovability", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Brylvar", name: "Gulbjarn's Betrayal", mana: 2, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Brylvar", name: "Shield Slam", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Brylvar", name: "Crawling Darkness", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Brylvar", name: "Mud Flood", mana: 3, modifier: +0, faction: "Taulot"},
{hero: "Astryda", name: "Freeze", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Astryda", name: "Bewitch", mana: 2, modifier: -1, faction: "Liothan"},
{hero: "Astryda", name: "Overflow", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Astryda", name: "Speak With The Spirits", mana: 2, modifier: +1, faction: "Liothan"},
{hero: "Astryda", name: "Icewall", mana: 3, modifier: +1, faction: "Liothan"},
{hero: "Astryda", name: "Song Of The Siren", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Astryda", name: "Triumph Of The Light", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Astryda", name: "Dismiss", mana: 2, modifier: -1, faction: "Nupten"},
{hero: "Astryda", name: "Where Faith Falls", mana: 1, modifier: +0, faction: "Nupten"},
{hero: "Astryda", name: "Windblast", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Gulbjarn", name: "Breath Of Life", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Gulbjarn", name: "The Hunt Begins", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Gulbjarn", name: "Speak With The Spirits", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Gulbjarn", name: "Feral Vitality", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Gulbjarn", name: "Granite Skin", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Gulbjarn", name: "Guerrilla Tactics", mana: 1, modifier: +1, faction: "Taulot"},
{hero: "Gulbjarn", name: "Gulbjarn's Betrayal", mana: 2, modifier: +1, faction: "Liothan/Taulot"},
{hero: "Gulbjarn", name: "Lord Of The Many", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Gulbjarn", name: "Guide", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Gulbjarn", name: "Rampant Hatred", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Shyllavi", name: "Psychic Shield", mana: 0, modifier: +3, faction: "Neutral"},
{hero: "Shyllavi", name: "Touch Of Liothan", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Shyllavi", name: "Call The Pack", mana: 2, modifier: +0, faction: "Liothan"},
{hero: "Shyllavi", name: "Dance Of The Predator", mana: 3, modifier: +3, faction: "Liothan"},
{hero: "Shyllavi", name: "Breath Of Life", mana: 1, modifier: +0, faction: "Liothan"},
{hero: "Shyllavi", name: "Acrobatics", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Shyllavi", name: "Time Glitch", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Shyllavi", name: "Nightmares Incarnate", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Shyllavi", name: "Chasm", mana: 3, modifier: +0, faction: "Liothan"},
{hero: "Shyllavi", name: "Twister Of Souls", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Kichie", name: "Psychic Vampirism", mana: 0, modifier: +2, faction: "Neutral"},
{hero: "Kichie", name: "Skytear Discharge", mana: 0, modifier: +2, faction: "Neutral"},
{hero: "Kichie", name: "Arena Of Flames", mana: 1, modifier: +0, faction: "Kurumo"},
{hero: "Kichie", name: "Mindfulness", mana: 1, modifier: +0, faction: "Kurumo"},
{hero: "Kichie", name: "Dance Of Death", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Kichie", name: "Curse Of Years", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Kichie", name: "Disrupt", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Kichie", name: "Shattermind", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Kichie", name: "Lure Of The Tainted", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Kichie", name: "Soul Scream", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Miyuki", name: "Decree Of Kurumo", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Miyuki", name: "Vendetta", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Miyuki", name: "Kurumo's Judgment", mana: 3, modifier: +1, faction: "Kurumo"},
{hero: "Miyuki", name: "Caged Soul", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Miyuki", name: "Exhaustion", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Miyuki", name: "Migraine", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Miyuki", name: "Purge And Purify", mana: 2, modifier: +0, faction: "Nupten"},
{hero: "Miyuki", name: "Where Faith Falls", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Miyuki", name: "Redirect", mana: 2, modifier: +1, faction: "Nupten"},
{hero: "Miyuki", name: "Twister Of Souls", mana: 3, modifier: +0, faction: "Nupten"},
{hero: "Sakoshi", name: "Clear Mind", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Sakoshi", name: "Smelt Armor", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Sakoshi", name: "Blazing Edge", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Sakoshi", name: "Lure Of The Tainted", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Sakoshi", name: "Kurumo's Judgment", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Sakoshi", name: "Shuriken Storm", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Sakoshi", name: "Impervious", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Sakoshi", name: "Reclaim Life", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Sakoshi", name: "Akimo's Oath", mana: 2, modifier: -1, faction: "Kurumo/Taulot"},
{hero: "Sakoshi", name: "Rampant Hatred", mana: 3, modifier: +1, faction: "Taulot"},
{hero: "Hogosai", name: "Down To Earth", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Hogosai", name: "Doom", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Hogosai", name: "Dissent In The Ranks", mana: 2, modifier: +1, faction: "Kurumo/Taulot"},
{hero: "Hogosai", name: "Lifesteal", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Hogosai", name: "Kurumo's Judgment", mana: 3, modifier: +1, faction: "Kurumo"},
{hero: "Hogosai", name: "Supernova", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Hogosai", name: "Reclaim Life", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Hogosai", name: "Shield Slam", mana: 1, modifier: +2, faction: "Taulot"},
{hero: "Hogosai", name: "Thorn Roots", mana: 2, modifier: +0, faction: "Taulot"},
{hero: "Hogosai", name: "Sinkhole", mana: 3, modifier: +0, faction: "Taulot"},
{hero: "Akimo", name: "Psychic Shield", mana: 0, modifier: +3, faction: "Neutral"},
{hero: "Akimo", name: "Crippling Precision", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Akimo", name: "Smelt Armor", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Akimo", name: "Blazing Edge", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Akimo", name: "Lure Of The Tainted", mana: 2, modifier: +1, faction: "Kurumo"},
{hero: "Akimo", name: "Demonic Possession", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Akimo", name: "Reave", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Akimo", name: "Unstoppable", mana: 3, modifier: +1, faction: "Kurumo"},
{hero: "Akimo", name: "Quicksand", mana: 2, modifier: +1, faction: "Taulot"},
{hero: "Akimo", name: "Akimo's Oath", mana: 2, modifier: -1, faction: "Kurumo/Taulot"},
{hero: "Yami", name: "Vendetta", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Yami", name: "Doom", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Yami", name: "Quick Shot", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Yami", name: "Seize The Initiative", mana: 1, modifier: +2, faction: "Kurumo"},
{hero: "Yami", name: "Disrupt", mana: 3, modifier: +0, faction: "Kurumo"},
{hero: "Yami", name: "Kneel Before Me", mana: 3, modifier: +3, faction: "Kurumo"},
{hero: "Yami", name: "Swiftness", mana: 1, modifier: +1, faction: "Nupten"},
{hero: "Yami", name: "Dance Of Death", mana: 1, modifier: +1, faction: "Kurumo"},
{hero: "Yami", name: "Time Glitch", mana: 1, modifier: +2, faction: "Nupten"},
{hero: "Yami", name: "Refract", mana: 3, modifier: +0, faction: "Nupten"},
];