
const ddmGBAList = [{
     name: "Blue-Eyes White Dragon",
     type: "Dragon",
     lvl: "4",
     hp: "50",
     atk: "40",
     def: "30",
     ability: "Flying",
     die1: "Sum",
     die2: "Mov",
     die3: "2Mov",
     die4: "4Atk",
     die5: "Def",
     die6: "Mag",
},
{
     name: "Mystical Elf",
     type: "Spellcaster",
     lvl: "1",
     hp: "20",
     atk: "10",
     def: "20",
     ability: "Effect: Restores 10HP to all allies (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "4Mag",
},
{
     name: "Hitotsu-Me Giant",
     type: "Beast",
     lvl: "2",
     hp: "10",
     atk: "20",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Atk",
     die5: "2Def",
     die6: "Mag",
},
{
     name: "Baby Dragon",
     type: "Dragon",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Flying. Effect: Immune to class-specific effects",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Atk",
     die6: "Mag",
},
{
     name: "Ryu-Kishin",
     type: "Spellcaster",
     lvl: "2",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "2Atk",
     die6: "2Atk",
},
{
     name: "Feral Imp",
     type: "Spellcaster",
     lvl: "2",
     hp: "10",
     atk: "10",
     def: "20",
     ability: "Effect: Prevents all flying (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "3Mov",
     die5: "5Atk",
     die6: "Def",
},
{
     name: "Winged Dragon, GotF #1",
     type: "Dragon",
     lvl: "2",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Flying. Effect: Prevents all tunneling (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "3Mov",
     die6: "Mag",
},
{
     name: "Mushroom Man",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Atk",
     die6: "Mag",
},
{
     name: "Shadow Spectar",
     type: "Undead",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Atk",
     die6: "Mag",
},
{
     name: "Swamp Battleguard",
     type: "Warrior",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "20",
     ability: "Effect: Pay one ATK Crest to raise ATK by 10 (upon attacking)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "2Atk",
     die6: "Tra",
},
{
     name: "Battle Steer",
     type: "Beast",
     lvl: "2",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "3Mov",
     die5: "Def",
     die6: "4Tra",
},
{
     name: "Flame Swordsman",
     type: "Warrior",
     lvl: "2",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "2Mov",
     die6: "2Atk",
},
{
     name: "Time Wizard",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "0",
     def: "10",
     ability: "Effect: Destroys monster with the least ATK (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "3Mov",
},
{
     name: "Right Leg Of Exodia",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "10",
     def: "0",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "3Mov",
     die5: "2Atk",
     die6: "Def",
},
{
     name: "Left Leg Of Exodia",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "10",
     def: "0",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "Atk",
     die5: "Def",
     die6: "Mag",
},
{
     name: "Right Arm Of Exodia",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "10",
     def: "0",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "3Mov",
     die5: "4Atk",
     die6: "2Def",
},
{
     name: "Left Arm Of Exodia",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "10",
     def: "0",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Exodia The Forbidden One",
     type: "Spellcaster",
     lvl: "4",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "Effect: Automatic win, if all 4 limbs are on the board (upon dimension)",
     die1: "Sum",
     die2: "Mov",
     die3: "7Mov",
     die4: "2Atk",
     die5: "4Def",
     die6: "Tra",
},
{
     name: "Summoned Skull",
     type: "Spellcaster",
     lvl: "4",
     hp: "40",
     atk: "40",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "3Mov",
     die3: "3Mov",
     die4: "Atk",
     die5: "Def",
     die6: "Mag",
},
{
     name: "Battle Ox",
     type: "Beast",
     lvl: "2",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "Def",
     die6: "2Mag",
},
{
     name: "Beaver Warrior",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "2Atk",
},
{
     name: "Rock Ogre Grotto #1",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raises DEF of all Spellcasters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mag",
     die6: "Tra",
},
{
     name: "Zombie Warrior",
     type: "Undead",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raises ATK of all Undead monsters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Atk",
     die6: "2Def",
},
{
     name: "Koumori Dragon",
     type: "Dragon",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Saggi The Dark Clown",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 2 DEF crests to reduce damage inflicted to any ally by 10",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Dark Magician",
     type: "Spellcaster",
     lvl: "4",
     hp: "30",
     atk: "40",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "2Mov",
     die3: "Atk",
​     die4: "2Def",
​     die5: "Mag",
​     die6: "Tra",
​ },
​ {
​     name: "The Snake Hair",
​     type: "Undead",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "Flying. Effect: Raises DEF of all Undead monsters by 10 (while in play)",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "Mov",
​     die6: "Mag",
​ },
​ {
​     name: "Gaia The Dragon Champion",
​     type: "Dragon",
​     lvl: "4",
​     hp: "40",
     atk: "40",
     def: "30",
     ability: "Flying",
     die1: "Sum",
     die2: "4Mov",
     die3: "3Atk",
     die4: "Def",
     die5: "2Mag",
     die6: "Tra",
},
{
     name: "Gaia The Fierce Knight",
     type: "Warrior",
     lvl: "4",
     hp: "40",
     atk: "40",
     def: "20",
     ability: "Archery",
     die1: "Sum",
     die2: "Mov",
     die3: "Atk",
     die4: "Def",
     die5: "3Mag",
     die6: "Tra",
},
{
     name: "Curse of Dragon",
     type: "Dragon",
     lvl: "3",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "Flying",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Mov",
     die5: "Atk",
     die6: "3Def",
},
{
     name: "Dragon Piper",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "0",
     def: "10",
     ability: "Effect: Limits all dragon monsters to 1 move every 2 turns (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Def",
     die6: "Mag",
},
{
     name: "Celtic Guardian",
     type: "Warrior",
     lvl: "2",
     hp: "10",
     atk: "20",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "3Mov",
     die5: "3Mag",
     die6: "Tra",
},
{
     name: "Faceless Mage",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "20",
     def: "30",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "3Mov",
     die4: "3Mov",
     die5: "Atk",
     die6: "2Def",
},
{
     name: "Karbonala Warrior",
     type: "Warrior",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raises ATK of all Warrior monsters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "Tra",
},
{
     name: "Rogue Doll",
     type: "Spellcaster",
     lvl: "3",
     hp: "20",
     atk: "30",
     def: "20",
     ability: "Effect: Pay 3 MAG Crests to restore 10 HP to 2 allied monsters (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "Atk",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Sangan",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Atk",
     die6: "4Mag",
},
{
     name: "Killer Needle",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Archery",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "Atk",
},
{
     name: "Giant Flea",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "20",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "Tra",
},
{
     name: "Larvae Moth",
     type: "Beast",
     lvl: "1",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "Def",
},
{
     name: "Great Moth",
     type: "Beast",
     lvl: "3",
     hp: "40",
     atk: "20",
     def: "30",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "2Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Kuriboh",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "4Atk",
     die6: "2Def",
},
{
     name: "Mammoth Graveyard",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Tunneling. Effect: Raises ATK of all Beast monsters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "5Mov",
     die6: "2Mag",
},
{
     name: "Harpie Lady",
     type: "Beast",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "10",
     ability: "Flying. Effect: Pay 3 MAG Crests to destroy 1 tunneling monster (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Mov",
     die6: "3Mag",
},
{
     name: "Harpie Lady Sisters",
     type: "Beast",
     lvl: "3",
     hp: "20",
     atk: "20",
     def: "20",
     ability: "Effect: Pay 4 MAG Crests to destroy all tunnelling monsters (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "3Atk",
     die5: "Def",
     die6: "2Tra",
},
{
     name: "Perfectly Ultimate",
     type: "Beast",
     lvl: "4",
     hp: "50",
     atk: "40",
     def: "40",
     ability: "Flying",
     die1: "Sum",
     die2: "4Mov",
     die3: "2Atk",
     die4: "Def",
     die5: "Tra",
     die6: "2Tra",
},
{
     name: "Thousand Dragon",
     type: "Dragon",
     lvl: "2",
     hp: "20",
     atk: "30",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "7Atk",
     die6: "Def",
},
{
     name: "Jellyfish",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raises DEF of all Beast monsters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "2Mag",
},
{
     name: "Cocoon of Evolution",
     type: "Beast",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "40",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Atk",
     die5: "Mag",
     die6: "3Tra",
},
{
     name: "Giant Rock Soldier",
     type: "Spellcaster",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "30",
     ability: "Effect: Pay 2 MAG Crests to destroy one obstacle from the board",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "2Atk",
     die6: "Tra",
},
{
     name: "Red-Eyes Black Dragon",
     type: "Dragon",
     lvl: "4",
     hp: "30",
     atk: "40",
     def: "20",
     ability: "Flying",
     die1: "Sum",
     die2: "2Mov",
     die3: "Atk",
     die4: "2Def",
     die5: "2Mag",
     die6: "2Tra",
},
{
     name: "Castle of D. Magic",
     type: "Spellcaster",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "20",
     ability: "Effect: Pay 2  Crests to reduce damage by 20 (when attacked)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Def",
     die6: "Def",
},
{
     name: "Metal Guardian",
     type: "Spellcaster",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "30",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Mystic Horseman",
     type: "Beast",
     lvl: "2",
     hp: "40",
     atk: "20",
     def: "10",
     ability: "Effect: Pay 1 MAG Crests to increase own ATK by 10 (once per turn)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Rabid Horseman",
     type: "Beast",
     lvl: "3",
     hp: "40",
     atk: "30",
     def: "20",
     ability: "Effect: Pay X ATK crests to increase own attack by X0 (during own attack)",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "2Atk",
     die5: "Def",
     die6: "Mag",
},
{
     name: "Clown Zombie",
     type: "Undead",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Tunneling. Effect: Immune to class-specific effects",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "4Tra",
},
{
     name: "Pumpking the King of Ghosts",
     type: "Undead",
     lvl: "3",
     hp: "30",
     atk: "20",
     def: "30",
     ability: "Effect: Pay 3 DEF Crests to reduce damage by 30 (when attacked)",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "2Atk",
     die5: "3Def",
     die6: "2Mag",
},
{
     name: "Battle Warrior",
     type: "Warrior",
     lvl: "1",
     hp: "20",
     atk: "20",
     def: "10",
     ability: "Archery. Effect: Add 1 ATK Crest to crest pool (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Atk",
     die6: "Mag",
},
{
     name: "The 13th Grave",
     type: "Undead",
     lvl: "2",
     hp: "10",
     atk: "0",
     def: "10",
     ability: "Tunneling. Effect: Pay 2 MAG Crests and sacrifice this monster to remove 10 HP from 1 enemy",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "7Mov",
     die5: "Atk",
     die6: "Mag",
},
{
     name: "Petit Dragon",
     type: "Dragon",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raise ATK of all Dragons by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Atk",
     die6: "Tra",
},
{
     name: "Aqua Madoor",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "2Atk",
​     die6: "Tra",
​ },
​ {
​     name: "Black Skull Dragon",
​     type: "Dragon",
​     lvl: "4",
​     hp: "40",
​     atk: "40",
​     def: "40",
​     ability: "Flying",
​     die1: "Sum",
​     die2: "3Mov",
​     die3: "Atk",
​     die4: "Atk",
​     die5: "3Def",
​     die6: "Mag",
​ },
​ {
​     name: "Beautiful Headhuntress",
​     type: "Warrior",
​     lvl: "3",
​     hp: "20",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "4Mov",
​     die4: "Def",
​     die5: "Def",
​     die6: "2Mag",
​ },
​ {
​     name: "Yaranzo",
​     type: "Undead",
​     lvl: "2",
​     hp: "20",
​     atk: "10",
​     def: "10",
​     ability: "Effect: Trade 3 crests in your pool for any one specific crest (upon dimension)",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "2Mov",
​     die5: "Atk",
​     die6: "Def",
​ },
​ {
​     name: "Kanan the Swordmistress",
​     type: "Warrior",
​     lvl: "2",
​     hp: "10",
​     atk: "20",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Mov",
​     die5: "Def",
​     die6: "Def",
​ },
​ {
​     name: "Stuffed Animal",
​     type: "Warrior",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "2Mov",
​     die6: "Def",
​ },
​ {
​     name: "Three-legged Zombies",
​     type: "Undead",
​     lvl: "1",
​     hp: "10",
​     atk: "20",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "Atk",
​     die6: "4Def",
​ },
​ {
​     name: "Flying Penguin",
​     type: "Beast",
​     lvl: "2",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Def",
​     die5: "Mag",
​     die6: "Tra",
​ },
​ {
​     name: "Millennium Shield",
​     type: "Warrior",
​     lvl: "3",
​     hp: "10",
​     atk: "0",
​     def: "40",
​     ability: "Effect: This monster cannot move",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "3Mov",
​     die4: "Atk",
​     die5: "3Atk",
​     die6: "4Def",
​ },
​ {
​     name: "Black Luster Soldier",
​     type: "Warrior",
​     lvl: "4",
​     hp: "50",
​     atk: "40",
​     def: "30",
​     ability: "",
​     die1: "Sum",
​     die2: "2Mov",
​     die3: "Atk",
​     die4: "Def",
​     die5: "Mag",
​     die6: "2Tra",
​ },
​ {
​     name: "Fiend's Mirror",
​     type: "Spellcaster",
​     lvl: "2",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
     die4: "Atk",
     die5: "2Def",
     die6: "2Tra",
},
{
     name: "Jirai Gumo",
     type: "Beast",
     lvl: "1",
     hp: "20",
     atk: "10",
     def: "10",
     ability: "Tunneling",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "6Def",
     die6: "Mag",
},
{
     name: "Sanga of the Thunder",
     type: "Spellcaster",
     lvl: "4",
     hp: "30",
     atk: "30",
     def: "30",
     ability: "Effect: Pay 3 TRA crests, to shift damage to an ally (when attacked)",
     die1: "Sum",
     die2: "Mov",
     die3: "3Mov",
     die4: "3Atk",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Kazejin",
     type: "Spellcaster",
     lvl: "4",
     hp: "30",
     atk: "30",
     def: "30",
     ability: "Effect: Pay 3 TRA crests, to shift damage to an ally (when attacked)",
     die1: "Sum",
     die2: "3Mov",
     die3: "Atk",
     die4: "Def",
     die5: "Mag",
     die6: "Tra",
},
{
     name: "Suijin",
     type: "Beast",
     lvl: "4",
     hp: "30",
     atk: "30",
     def: "30",
     ability: "Effect: Pay 3 TRA crests, to shift damage to an ally (when attacked)",
     die1: "Sum",
     die2: "Mov",
     die3: "Atk",
     die4: "2Def",
     die5: "Mag",
     die6: "Tra",
},
{
     name: "Gate Guardian",
     type: "Warrior",
     lvl: "4",
​     hp: "50",
​     atk: "40",
​     def: "40",
​     ability: "Effect: Pay 3 TRA crests, to shift damage to an ally (when attacked)",
​     die1: "Sum",
​     die2: "2Mov",
​     die3: "Atk",
​     die4: "2Def",
​     die5: "3Mag",
​     die6: "2Tra",
​ },
​ {
​     name: "Ryu-kishin Powered",
​     type: "Spellcaster",
​     lvl: "2",
​     hp: "20",
​     atk: "30",
​     def: "20",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "2Mov",
​     die5: "Atk",
​     die6: "Def",
​ },
​ {
​     name: "Blue-Eyes Ultimate Dragon",
​     type: "Dragon",
​     lvl: "4",
​     hp: "60",
​     atk: "50",
​     def: "40",
​     ability: "Effect: This monster can only move 1 square per turn",
​     die1: "Sum",
​     die2: "Mov",
​     die3: "Atk",
​     die4: "Def",
​     die5: "2Mag",
​     die6: "Tra",
​ },
​ {
​     name: "Parrot Dragon",
​     type: "Dragon",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "Flying. Effect: Raise DEF of all Dragons by 10 (while in play)",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "2Mov",
​     die6: "Tra",
​ },
​ {
​     name: "Mystic Lamp",
​     type: "Spellcaster",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "Effect: Raise ATK of all Spellcaster monsters by 10 (while in play)",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "Mag",
​     die6: "Mag",
​ },
​ {
​     name: "Pendulum Machine",
​     type: "Spellcaster",
​     lvl: "3",
​     hp: "20",
​     atk: "20",
​     def: "30",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Mov",
​     die4: "Atk",
​     die5: "3Mag",
​     die6: "Tra",
​ },
​ {
​     name: "Zoa",
​     type: "Spellcaster",
​     lvl: "3",
​     hp: "20",
​     atk: "30",
​     def: "20",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "4Mov",
​     die4: "Atk",
​     die5: "Def",
​     die6: "2Def",
​ },
​ {
​     name: "Metalzoa",
​     type: "Spellcaster",
​     lvl: "4",
​     hp: "30",
​     atk: "30",
​     def: "30",
​     ability: "",
​     die1: "Sum",
​     die2: "8Mov",
​     die3: "Atk",
​     die4: "8Def",
​     die5: "Mag",
​     die6: "4Tra",
​ },
​ {
​     name: "Dancing Elf",
​     type: "Warrior",
​     lvl: "1",
​     hp: "20",
​     atk: "20",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "Atk",
​     die6: "Mag",
​ },
​ {
​     name: "Man-eater Bug",
​     type: "Beast",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "Mov",
​     die6: "2Atk",
},
{
     name: "Gemini Elf",
     type: "Spellcaster",
     lvl: "3",
     hp: "10",
     atk: "40",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "Atk",
     die5: "3Def",
     die6: "4Tra",
},
{
     name: "Skelengel",
     type: "Warrior",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Raise DEF of all Warrior monsters by 10 (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "Mag",
},
{
     name: "Hane-Hane",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "4Def",
     die6: "Mag",
},
{
     name: "Penguin Soldier",
     type: "Beast",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "3Mov",
},
{
     name: "Twin-headed Thunder Dragon",
     type: "Dragon",
     lvl: "3",
     hp: "20",
     atk: "40",
     def: "20",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Mov",
​     die4: "2Atk",
​     die5: "2Mag",
​     die6: "2Tra",
​ },
​ {
​     name: "Witch's Apprentice",
​     type: "Spellcaster",
​     lvl: "1",
​     hp: "10",
​     atk: "10",
​     def: "10",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Sum",
​     die4: "Sum",
​     die5: "2Mov",
​     die6: "Tra",
​ },
​ {
​     name: "Meteor Dragon",
​     type: "Dragon",
​     lvl: "3",
​     hp: "30",
​     atk: "20",
​     def: "30",
​     ability: "Flying",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "3Mov",
​     die4: "4Mov",
​     die5: "Def",
​     die6: "Mag",
​ },
​ {
​     name: "Meteor B. Dragon",
​     type: "Dragon",
​     lvl: "4",
​     hp: "30",
​     atk: "40",
​     def: "20",
​     ability: "Flying",
​     die1: "Sum",
​     die2: "Mov",
​     die3: "Atk",
​     die4: "Def",
​     die5: "Mag",
​     die6: "Tra",
​ },
​ {
​     name: "Dokurorider",
​     type: "Undead",
​     lvl: "3",
​     hp: "20",
​     atk: "20",
​     def: "20",
​     ability: "",
​     die1: "Sum",
​     die2: "Sum",
​     die3: "Mov",
​     die4: "Atk",
     die5: "2Def",
     die6: "2Mag",
},
{
     name: "Magician of Black Chaos",
     type: "Spellcaster",
     lvl: "4",
     hp: "40",
     atk: "40",
     def: "30",
     ability: "",
     die1: "Sum",
     die2: "Mov",
     die3: "2Atk",
     die4: "Def",
     die5: "Mag",
     die6: "Tra",
},
{
     name: "Slot Machine",
     type: "Spellcaster",
     lvl: "3",
     hp: "30",
     atk: "20",
     def: "20",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "2Atk",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Red Archery Girl",
     type: "Warrior",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "2Def",
},
{
     name: "Dark-eyes Illusionist",
     type: "Spellcaster",
     lvl: "4",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 5 TRA crests to negate an attack or effect on 1 ally",
     die1: "Sum",
     die2: "Mov",
     die3: "2Atk",
     die4: "2Def",
     die5: "Mag",
     die6: "3Tra",
},
{
     name: "Relinquished",
     type: "Spellcaster",
     lvl: "1",
     hp: "10",
     atk: "0",
     def: "0",
     ability: "Effect: Pay 10 TRA crests and sacrifice this monster to steal 1 enemy monster",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Def",
     die6: "3Tra",
},
{
     name: "Thousand-eyes Restrict",
     type: "Spellcaster",
     lvl: "4",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 8 TRA crests to gain control of 1 foe, for the rest of the turn",
     die1: "Sum",
     die2: "2Mov",
     die3: "Atk",
     die4: "2Def",
     die5: "5Mag",
     die6: "Tra",
},
{
     name: "Lord of D",
     type: "Spellcaster",
     lvl: "2",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Effect: Protects all Dragons (while in play)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Atk",
     die6: "2Mag",
},
{
     name: "Red-Eyes Black Metal Dragon",
     type: "Dragon",
     lvl: "4",
     hp: "30",
     atk: "40",
     def: "40",
     ability: "Flying",
     die1: "Sum",
     die2: "2Mov",
     die3: "Atk",
     die4: "Def",
     die5: "3Mag",
     die6: "2Tra",
},
{
     name: "Barrel Dragon",
     type: "Dragon",
     lvl: "4",
     hp: "40",
     atk: "30",
     def: "30",
     ability: "",
     die1: "Sum",
     die2: "6Mov",
     die3: "Def",
     die4: "Mag",
     die5: "2Tra",
     die6: "2Tra",
},
{
     name: "Jinzo",
     type: "Warrior",
     lvl: "3",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Atk",
     die5: "2Def",
     die6: "Tra",
},
{
     name: "Dark Magician Girl",
     type: "Spellcaster",
     lvl: "3",
     hp: "20",
     atk: "20",
     def: "10",
     ability: "Effect: Inherits the ATK and DEF of all destroyed Spellcaster monsters",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "Atk",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Twin-Headed Dragon",
     type: "Undead",
     lvl: "1",
     hp: "10",
     atk: "10",
     def: "10",
     ability: "Tunneling. Effect: All 1 TRA crest to your crest pool (upon dimension)",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Def",
     die6: "2Mag",
},
{
     name: "Gator Dragon",
     type: "Dragon",
     lvl: "2",
     hp: "30",
     atk: "10",
     def: "10",
     ability: "Effect: Pay X DEF to reduce the damage of an attack by 10X",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Blast Lizard",
     type: "Beast",
     lvl: "2",
     hp: "20",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 3 TRA crests to destroy 1 X monster. Gain X MAG crests",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Atk",
     die5: "Def",
     die6: "4Tra",
},
{
     name: "Knight Of Twin Swords",
     type: "Warrior",
     lvl: "2",
     hp: "30",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 1 Mov crest to move 2 spaces. Attacks up to 3 times per turn",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Thunder Ball",
     type: "Spellcaster",
     lvl: "3",
     hp: "30",
     atk: "10",
     def: "10",
     ability: "Effect: Pay 3 TRA crests to destroy 1 X monster. Gain X MAG crests",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Mov",
     die5: "2Atk",
     die6: "2Def",
},
{
     name: "Magician Dragon",
     type: "Dragon",
     lvl: "3",
     hp: "40",
     atk: "20",
     def: "10",
     ability: "Effect: Pay 3 TRA crests to add enemy's DEF to own DEF. Effect: Pay 3 MAG crests to destroy everything within a 3x3 grid",
     die1: "Sum",
     die2: "Sum",
     die3: "4Mov",
     die4: "Atk",
     die5: "Def",
     die6: "3Def",
},
{
     name: "Strike Ninja",
     type: "Warrior",
     lvl: "3",
     hp: "20",
     atk: "20",
     def: "10",
     ability: "Effect: Move 3 squares per MOV crest. Effect: Pay 2 TRA crest to protect self from attacks and effects",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Mov",
     die5: "Atk",
     die6: "Def",
},
{
     name: "Mighty Mage",
     type: "Spellcaster",
     lvl: "4",
     hp: "50",
     atk: "30",
     def: "20",
     ability: "Effect: Pay 1 MAG crest to attack an enemy 2 squares away",
     die1: "Sum",
     die2: "2Mov",
     die3: "4Mov",
     die4: "Atk",
     die5: "Mag",
     die6: "Tra",
},
{
     name: "Crocozaurus",
     type: "Beast",
     lvl: "4",
     hp: "50",
     atk: "30",
     def: "20",
     ability: "Effect: Pay X ATK crests to raise ATK by 10X (upon attack, 3 times per turn)",
     die1: "Sum",
     die2: "Mov",
     die3: "2Atk",
     die4: "Def",
     die5: "Mag",
     die6: "3Tra",
},
{
     name: "Orgoth The Relentless",
     type: "Warrior",
     lvl: "3",
     hp: "30",
     atk: "20",
     def: "20",
     ability: "Effect: Pay 2 MAG crests to raise ATK by 10",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "3Mov",
     die5: "2Atk",
     die6: "Def",
},
{
     name: "Medical Aid Kid",
     type: "Item",
     lvl: "2",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Restores 20 HP to a monster",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "5Mov",
     die5: "Atk",
     die6: "Tra",
},
{
     name: "Exploding Disc",
     type: "Item",
     lvl: "3",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Removes 20 HP from a monster",
     die1: "Sum",
     die2: "Sum",
     die3: "2Mov",
     die4: "3Mov",
     die5: "2Def",
     die6: "2Mag",
},
{
     name: "Time Machine",
     type: "Item",
     lvl: "1",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Returns a monster to its last location",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Sum",
     die6: "Tra",
},
{
     name: "Energy Disc",
     type: "Item",
     lvl: "1",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Raises a monster's ATK by 20",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "3Mov",
     die6: "4Mov",
},
{
     name: "Trap Bandit",
     type: "Item",
     lvl: "1",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Destroys one TRA crest in player's crest pool",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "Mov",
     die6: "Tra",
},
{
     name: "Declaration of Despair",
     type: "Item",
     lvl: "1",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Destroys one MAG crest in player's crest pool",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "Sum",
     die5: "2Mov",
     die6: "Mag",
},
{
     name: "Gluminizer",
     type: "Item",
     lvl: "2",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Doubles movement costs of all monsters",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "Atk",
     die6: "2Def",
},
{
     name: "Resurrection Scroll",
     type: "Item",
     lvl: "2",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Resurrects 1 destroyed monster",
     die1: "Sum",
     die2: "Sum",
     die3: "Sum",
     die4: "2Mov",
     die5: "2Mag",
     die6: "Tra",
},
{
     name: "Warp Vortex",
     type: "Item",
     lvl: "3",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Transports monster to another Warp Vortex",
     die1: "Sum",
     die2: "Sum",
     die3: "Mov",
     die4: "Atk",
     die5: "Def",
     die6: "Tra",
},
{
     name: "Crater Creator",
     type: "Item",
     lvl: "4",
     hp: "",
     atk: "",
     def: "",
     ability: "Effect: Destroys all monsters in the dungeon",
     die1: "Sum",
     die2: "4Mov",
     die3: "Atk",
     die4: "2Atk",
     die5: "Def",
     die6: "4Mag",
},
]